//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_CUSTOMER
    {
        public decimal NO { get; set; }
        public decimal ARTNO { get; set; }
        public decimal CONO { get; set; }
        public string CUSTADDITION { get; set; }
        public string CUSTNAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> EPROZ0 { get; set; }
        public Nullable<decimal> EPROZ1 { get; set; }
        public Nullable<decimal> EPROZ2 { get; set; }
        public Nullable<decimal> EPROZ3 { get; set; }
        public Nullable<decimal> EPROZ4 { get; set; }
        public Nullable<decimal> EPROZ5 { get; set; }
        public string INFO { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> STATUS0 { get; set; }
        public Nullable<decimal> STATUS1 { get; set; }
        public Nullable<decimal> STATUS2 { get; set; }
        public Nullable<decimal> STATUS3 { get; set; }
        public Nullable<decimal> STATUS4 { get; set; }
        public Nullable<decimal> STATUS5 { get; set; }
        public Nullable<decimal> VERSNO { get; set; }
        public Nullable<decimal> VERTID { get; set; }
        public string VERTRNAME { get; set; }
        public string VKCNTRYSIGN { get; set; }
        public string VKCNTRYSIGNF { get; set; }
        public Nullable<decimal> VKMENGE0 { get; set; }
        public Nullable<decimal> VKMENGE1 { get; set; }
        public Nullable<decimal> VKMENGE2 { get; set; }
        public Nullable<decimal> VKMENGE3 { get; set; }
        public Nullable<decimal> VKMENGE4 { get; set; }
        public Nullable<decimal> VKMENGE5 { get; set; }
        public Nullable<decimal> VKPREIS0 { get; set; }
        public Nullable<decimal> VKPREIS1 { get; set; }
        public Nullable<decimal> VKPREIS2 { get; set; }
        public Nullable<decimal> VKPREIS3 { get; set; }
        public Nullable<decimal> VKPREIS4 { get; set; }
        public Nullable<decimal> VKPREIS5 { get; set; }
        public Nullable<decimal> VKPREISF0 { get; set; }
        public Nullable<decimal> VKPREISF1 { get; set; }
        public Nullable<decimal> VKPREISF2 { get; set; }
        public Nullable<decimal> VKPREISF3 { get; set; }
        public Nullable<decimal> VKPREISF4 { get; set; }
        public Nullable<decimal> VKPREISF5 { get; set; }
        public string VKWAEHRUNG { get; set; }
        public string VKWAEHRUNGF { get; set; }
        public Nullable<decimal> VPROV { get; set; }
        public Nullable<decimal> VPROZ0 { get; set; }
        public Nullable<decimal> VPROZ1 { get; set; }
        public Nullable<decimal> VPROZ2 { get; set; }
        public Nullable<decimal> VPROZ3 { get; set; }
        public Nullable<decimal> VPROZ4 { get; set; }
        public Nullable<decimal> VPROZ5 { get; set; }
        public Nullable<decimal> VRABATT { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
