//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditItem
    {
        public int AuditItem_Reference { get; set; }
        public Nullable<System.DateTime> Date_Of_Activity { get; set; }
        public string Auditor { get; set; }
        public string Outcome { get; set; }
        public Nullable<int> Audit_Reference { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
    }
}
