//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CAPACITY
    {
        public decimal CAPNO { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public decimal WPLACE { get; set; }
        public string WPLACENAME { get; set; }
        public Nullable<decimal> WMULTI { get; set; }
        public string WMULTINAME { get; set; }
        public Nullable<decimal> WGROUP { get; set; }
        public string WGROUPNAME { get; set; }
        public Nullable<decimal> CAPACITY1 { get; set; }
        public Nullable<decimal> CAPACITY2 { get; set; }
        public Nullable<decimal> CAPACITY3 { get; set; }
        public Nullable<decimal> CAPACITY4 { get; set; }
        public Nullable<decimal> CAPACITY5 { get; set; }
        public Nullable<decimal> CAPACITY6 { get; set; }
        public Nullable<decimal> CAPACITY7 { get; set; }
        public Nullable<decimal> MAX1 { get; set; }
        public Nullable<decimal> MAX2 { get; set; }
        public Nullable<decimal> MAX3 { get; set; }
        public Nullable<decimal> MAX4 { get; set; }
        public Nullable<decimal> MAX5 { get; set; }
        public Nullable<decimal> MAX6 { get; set; }
        public Nullable<decimal> MAX7 { get; set; }
        public Nullable<decimal> START1 { get; set; }
        public Nullable<decimal> START2 { get; set; }
        public Nullable<decimal> START3 { get; set; }
        public Nullable<decimal> START4 { get; set; }
        public Nullable<decimal> START5 { get; set; }
        public Nullable<decimal> START6 { get; set; }
        public Nullable<decimal> START7 { get; set; }
        public Nullable<decimal> WEEKPLAN { get; set; }
        public string WPLANNAME { get; set; }
        public Nullable<decimal> HOLIDAYTYP { get; set; }
        public string HOLIDAYTXT { get; set; }
        public Nullable<decimal> TYP { get; set; }
        public Nullable<decimal> PERSON { get; set; }
        public System.DateTime CDATE { get; set; }
        public string SBREAK { get; set; }
    }
}
