//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_HOLIDAY
    {
        public decimal HOLNO { get; set; }
        public System.DateTime DAYDATE { get; set; }
        public Nullable<decimal> TYP { get; set; }
        public string DESCR { get; set; }
    }
}
