//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_WEEKPLAN
    {
        public decimal WPNO { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CAPDAY1 { get; set; }
        public Nullable<decimal> CAPDAY2 { get; set; }
        public Nullable<decimal> CAPDAY3 { get; set; }
        public Nullable<decimal> CAPDAY4 { get; set; }
        public Nullable<decimal> CAPDAY5 { get; set; }
        public Nullable<decimal> CAPDAY6 { get; set; }
        public Nullable<decimal> CAPDAY7 { get; set; }
        public Nullable<decimal> MAXDAY1 { get; set; }
        public Nullable<decimal> MAXDAY2 { get; set; }
        public Nullable<decimal> MAXDAY3 { get; set; }
        public Nullable<decimal> MAXDAY4 { get; set; }
        public Nullable<decimal> MAXDAY5 { get; set; }
        public Nullable<decimal> MAXDAY6 { get; set; }
        public Nullable<decimal> MAXDAY7 { get; set; }
        public Nullable<decimal> START1 { get; set; }
        public Nullable<decimal> START2 { get; set; }
        public Nullable<decimal> START3 { get; set; }
        public Nullable<decimal> START4 { get; set; }
        public Nullable<decimal> START5 { get; set; }
        public Nullable<decimal> START6 { get; set; }
        public Nullable<decimal> START7 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public string SBREAK { get; set; }
        public Nullable<decimal> GROUPNO { get; set; }
    }
}
