//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationEquipment
    {
        public int Calibration_Equipment_Ref { get; set; }
        public string Equipment_Prefix { get; set; }
        public Nullable<int> Equipment_Number { get; set; }
        public string Equipment_Suffix { get; set; }
        public Nullable<int> Calibration_Procedure_Ref { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> Date_Purchased { get; set; }
        public Nullable<System.DateTime> Date_First_Active { get; set; }
        public string Calibration_Period { get; set; }
        public Nullable<int> Calibration_Interval { get; set; }
        public string Check_Period { get; set; }
        public Nullable<int> Check_Interval { get; set; }
        public string Colour_Code { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date_Last_Calibration { get; set; }
        public Nullable<System.DateTime> Date_Next_Calibration { get; set; }
        public Nullable<System.DateTime> Date_Last_Check { get; set; }
        public Nullable<System.DateTime> Date_Next_Check { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<System.DateTime> Date_Last_Active { get; set; }
        public Nullable<double> Uses_Before_Calibration { get; set; }
        public Nullable<double> Uses_Before_Check { get; set; }
        public Nullable<double> Used_Since_Calibration { get; set; }
        public Nullable<double> Used_Since_Check { get; set; }
        public Nullable<double> Notifier_Offset_Cal { get; set; }
        public Nullable<double> Activity_Date_Offset_Cal { get; set; }
        public Nullable<double> Notifier_Offset_Chk { get; set; }
        public Nullable<double> Activity_Date_Offset_Chk { get; set; }
    }
}
