//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationUsage
    {
        public int Calibration_Usage_Ref { get; set; }
        public Nullable<int> Worder_Reference { get; set; }
        public string User_Reference { get; set; }
        public Nullable<System.DateTime> Date_Out { get; set; }
        public Nullable<System.DateTime> Date_In { get; set; }
        public Nullable<System.DateTime> Employee_Reference { get; set; }
        public string Employee_Name { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Calibration_Equipment_Ref { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
        public Nullable<int> Number_Of_Uses { get; set; }
    }
}
