//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Client_Reference { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public System.DateTime Installation_Date { get; set; }
        public string Quote_User_Reference { get; set; }
        public string WOrder_User_Reference { get; set; }
        public string DNote_User_Reference { get; set; }
        public string Invoice_User_Reference { get; set; }
        public string POrder_User_Reference { get; set; }
        public string Batch_User_Reference { get; set; }
        public bool Evaluation { get; set; }
        public Nullable<int> Number_Of_Records { get; set; }
        public Nullable<int> Number_Of_Days { get; set; }
        public Nullable<int> Warn_At { get; set; }
        public string VAT_Number { get; set; }
        public Nullable<int> VAT_Reference { get; set; }
        public string External_Nominal { get; set; }
        public string External_Department { get; set; }
        public string External_Tax_Code { get; set; }
        public bool Default_Record { get; set; }
        public byte[] Document_Header { get; set; }
        public byte[] Document_Footer { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Last_Modified { get; set; }
        public string Part_Batch_Number { get; set; }
        public string Material_Batch_Number { get; set; }
        public string Password { get; set; }
        public Nullable<int> Active_Colour { get; set; }
        public Nullable<int> Mandatory_Colour { get; set; }
        public string Subcontract_Batch_Number { get; set; }
        public string Tooling_Batch_Number { get; set; }
        public string Mat_Calc_Type { get; set; }
        public bool CloseInterimBatch { get; set; }
        public bool BarCodeActive { get; set; }
        public bool QUnfinished { get; set; }
        public bool QIssued { get; set; }
        public bool QAccepted { get; set; }
        public bool QRejected { get; set; }
        public bool QCancelled { get; set; }
        public bool WUnfinished { get; set; }
        public bool WIssued { get; set; }
        public bool WOffSite { get; set; }
        public bool WDelivered { get; set; }
        public bool WInvoiced { get; set; }
        public bool WCancelled { get; set; }
        public bool WTemplate { get; set; }
        public Nullable<int> OperationIncrement { get; set; }
        public bool LockRef { get; set; }
        public bool WarnRef { get; set; }
        public bool LockTemplate { get; set; }
        public bool StopTemplateCopy { get; set; }
        public bool LockWorksOrders { get; set; }
        public bool StopWorksOrderCopy { get; set; }
        public bool DisplayQuarantine { get; set; }
        public bool Suppliers_Approved { get; set; }
        public bool Customers_Approved { get; set; }
        public bool QTemplate { get; set; }
        public bool AutoDelivery { get; set; }
        public bool AutoInvoice { get; set; }
        public bool FlagInvoiceOnDelivery { get; set; }
        public bool AutoStatusOnQuotes { get; set; }
        public bool AutoStatusOnWOrders { get; set; }
        public bool AuotoMoveToDelivered { get; set; }
        public Nullable<double> QuotesUpliftPercentage { get; set; }
        public bool ConsolidateMaterials { get; set; }
        public bool AutoDeliveryUpdate { get; set; }
        public Nullable<double> EuroConversionRate { get; set; }
        public bool AutoWOAlign { get; set; }
        public bool CheckAllOpsComplete { get; set; }
        public bool CheckLastOpComplete { get; set; }
        public bool CheckMaterials { get; set; }
        public bool CheckParts { get; set; }
        public bool CheckSubContract { get; set; }
        public bool CheckTooling { get; set; }
        public bool CheckBatches { get; set; }
        public bool CheckPOInserts { get; set; }
        public bool AutoDeliveryTrace { get; set; }
        public bool AutoDeliveryRequired { get; set; }
        public bool AutoDeliveryDateMove { get; set; }
        public bool NumberTemplates { get; set; }
        public Nullable<bool> DisplayPartStock { get; set; }
        public string RTEFontName { get; set; }
        public Nullable<int> RTEFontSize { get; set; }
        public string MasterPassword { get; set; }
        public string AccessPassword { get; set; }
        public bool PasswordProtect { get; set; }
        public bool EditPurchaseOrder { get; set; }
        public bool Permit_Email { get; set; }
        public Nullable<int> WOrder_Amber_Days { get; set; }
        public Nullable<bool> Show_WOrder_Colours { get; set; }
        public Nullable<bool> Scheduler_Enabled { get; set; }
        public string External_Program_Path { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileExt { get; set; }
        public Nullable<bool> Print_External { get; set; }
        public string Batch_File { get; set; }
        public string View_File_Extension { get; set; }
        public string File_To_Print_Two { get; set; }
        public string File_Name_Separator { get; set; }
        public string Plot_Separator { get; set; }
        public string Plot_Part_Two { get; set; }
        public Nullable<bool> Nominal_Code_Mandatory { get; set; }
        public Nullable<bool> Trace_On_WO_Batches { get; set; }
        public Nullable<bool> Allow_Multiple_WoBatch_AddToStock { get; set; }
        public Nullable<bool> Edit_Porder_Partnum_Issue { get; set; }
        public Nullable<bool> FlagWhenNotApproved { get; set; }
        public string NotApprovedError { get; set; }
        public Nullable<bool> AutoInvoicedAssemblyComponents { get; set; }
        public bool EndUser_Enabled { get; set; }
        public string Proforma_User_Reference { get; set; }
        public Nullable<bool> ConsolidatePO { get; set; }
        public Nullable<bool> DirectEmailQuotes { get; set; }
        public Nullable<bool> DirectEmailPO { get; set; }
        public Nullable<bool> DirectEmailOrderAck { get; set; }
        public Nullable<bool> DirectEmailCOC { get; set; }
        public string QuoteMailSubject { get; set; }
        public string QuoteMailBody { get; set; }
        public string POMailSubject { get; set; }
        public string POMailBody { get; set; }
        public string OrderAckMailSubject { get; set; }
        public string OrderAckMailBody { get; set; }
        public string COCMailSubject { get; set; }
        public string COCMailBody { get; set; }
        public bool Quantity_Ops_Close { get; set; }
        public bool Copy_Notes_On_PO { get; set; }
        public bool Round_Quotes { get; set; }
        public bool Quote_Round_Up { get; set; }
        public string InvoiceMailSubject { get; set; }
        public string InvoiceMailBody { get; set; }
        public string DeliveryNoteMailSubject { get; set; }
        public string DeliveryNoteMailBody { get; set; }
        public Nullable<bool> DirectEmailInvoices { get; set; }
        public Nullable<bool> DirectEmailDeliveryNotes { get; set; }
        public Nullable<int> message_opacity { get; set; }
        public Nullable<int> message_Delay { get; set; }
        public bool Auto_Quarantine_Material { get; set; }
        public bool Auto_Quarantine_Part { get; set; }
        public string RFQ_User_Reference { get; set; }
        public Nullable<bool> external_T_and_A { get; set; }
        public Nullable<bool> StopWhenNotClockedIn { get; set; }
        public Nullable<System.DateTime> DefaultShiftStartTime { get; set; }
        public Nullable<System.DateTime> AutoCloseTime { get; set; }
        public Nullable<bool> AutoSetQuotesAsAccepted { get; set; }
        public Nullable<bool> AutoSetQuotesAsRejected { get; set; }
        public Nullable<int> MassInvoicingDefaultDateOption { get; set; }
        public string CentralConfigFolderPath { get; set; }
        public string GoogleMapsURL { get; set; }
        public Nullable<bool> bRichPItemNotes { get; set; }
        public string MasterPC { get; set; }
        public Nullable<bool> AutoClientUpdate { get; set; }
        public string CopyWOAttachments { get; set; }
        public string CopyQuoteAttachments { get; set; }
        public string CopyWOTemplateAttachments { get; set; }
        public string CopyQuoteTemplateAttachments { get; set; }
        public Nullable<int> MinMarkup { get; set; }
        public Nullable<bool> AutoUnlockWoCopy { get; set; }
        public Nullable<bool> AutoUnlockTemplateCopy { get; set; }
        public Nullable<bool> AllowChangeInvoiceToCredit { get; set; }
        public Nullable<bool> AllowEditBatchQtyIfCreditInvoice { get; set; }
        public int JitOffSetDays { get; set; }
        public int JitOffSetTimeOfDaySecs { get; set; }
        public bool UseJitOffsetTime { get; set; }
        public string AppDataLocationType { get; set; }
    }
}
