//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_ACCOUNT
    {
        public decimal NO { get; set; }
        public Nullable<decimal> FKNO { get; set; }
        public Nullable<decimal> FKTYP { get; set; }
        public string ACCOUNTNO { get; set; }
        public string BANKID { get; set; }
        public string BANKNAME { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public string IBAN { get; set; }
        public string SWIFT { get; set; }
        public string INF0 { get; set; }
        public string INF1 { get; set; }
        public string INF2 { get; set; }
        public string INF3 { get; set; }
    }
}
