//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_BEM
    {
        public decimal BEMNO { get; set; }
        public Nullable<System.DateTime> BEMDATE { get; set; }
        public Nullable<decimal> BEMINDX { get; set; }
        public string BEMINF0 { get; set; }
        public Nullable<decimal> BEMNUM { get; set; }
        public Nullable<decimal> BEMTYP { get; set; }
        public Nullable<decimal> CONO { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
