//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_CNTRY
    {
        public string CNTRYSIGN { get; set; }
        public string ADDRDTEXT { get; set; }
        public string ADDRTEXT { get; set; }
        public Nullable<decimal> ADDRTYPE { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> ECONOMICAREA { get; set; }
        public Nullable<decimal> GMTINDEX { get; set; }
        public string ISO2CC { get; set; }
        public string ISO3CC { get; set; }
        public string NAME { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
