//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_COTYP
    {
        public decimal COTYPNO { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string TEXT { get; set; }
        public Nullable<decimal> TYP0 { get; set; }
        public Nullable<decimal> TYP1 { get; set; }
        public Nullable<decimal> TYP2 { get; set; }
        public Nullable<decimal> TYP3 { get; set; }
        public Nullable<decimal> TYP4 { get; set; }
        public Nullable<decimal> TYP5 { get; set; }
        public Nullable<decimal> TYP6 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
