//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_INFO
    {
        public decimal INFONO { get; set; }
        public decimal CONO { get; set; }
        public decimal PERSNO { get; set; }
        public string MESSAGE { get; set; }
        public string ADRADDITION { get; set; }
        public string ADRCNTRYSIGN { get; set; }
        public string ADRCUSTNO { get; set; }
        public string ADRFAX { get; set; }
        public string ADRIDENT { get; set; }
        public string ADRNAME { get; set; }
        public string ADRPDEPARTM { get; set; }
        public string ADRPFAX { get; set; }
        public string ADRPFIRSTNAME { get; set; }
        public string ADRPHONE { get; set; }
        public string ADRPLACE { get; set; }
        public string ADRPMODEM { get; set; }
        public string ADRPOSTCODE { get; set; }
        public string ADRPPHONE1 { get; set; }
        public string ADRPPHONE2 { get; set; }
        public string ADRPPHONE3 { get; set; }
        public string ADRPPHONE4 { get; set; }
        public string ADRPPHONE5 { get; set; }
        public string ADRPPHONE6 { get; set; }
        public Nullable<decimal> ADRPSEX { get; set; }
        public string ADRPSURNAME { get; set; }
        public string ADRPTITLE { get; set; }
        public string ADRSECPHONE { get; set; }
        public string ADRSTREET { get; set; }
        public Nullable<decimal> AUSGMAIL { get; set; }
        public string INFOLINE { get; set; }
        public string INFONAME { get; set; }
        public Nullable<System.DateTime> INFOREADY { get; set; }
        public Nullable<decimal> INFOSTATUS { get; set; }
        public Nullable<System.DateTime> INFOTIME { get; set; }
        public Nullable<decimal> INFOTYP { get; set; }
        public Nullable<decimal> IREAD { get; set; }
        public Nullable<decimal> SALESMAN { get; set; }
        public string SALESNAME { get; set; }
        public Nullable<decimal> SENDTO { get; set; }
        public string SENDTONAME { get; set; }
        public Nullable<decimal> TYP { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public Nullable<decimal> XREAD { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
