//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_MAIL
    {
        public decimal MAILNO { get; set; }
        public decimal INFONO { get; set; }
        public decimal INFOTYP { get; set; }
        public string INFOTEXT { get; set; }
    }
}
