//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_PERS
    {
        public decimal PERSNO { get; set; }
        public decimal CONO { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> CHECK0 { get; set; }
        public Nullable<decimal> CHECK1 { get; set; }
        public Nullable<decimal> CHECK10 { get; set; }
        public Nullable<decimal> CHECK11 { get; set; }
        public Nullable<decimal> CHECK12 { get; set; }
        public Nullable<decimal> CHECK13 { get; set; }
        public Nullable<decimal> CHECK14 { get; set; }
        public Nullable<decimal> CHECK15 { get; set; }
        public Nullable<decimal> CHECK16 { get; set; }
        public Nullable<decimal> CHECK17 { get; set; }
        public Nullable<decimal> CHECK18 { get; set; }
        public Nullable<decimal> CHECK19 { get; set; }
        public Nullable<decimal> CHECK2 { get; set; }
        public Nullable<decimal> CHECK20 { get; set; }
        public Nullable<decimal> CHECK21 { get; set; }
        public Nullable<decimal> CHECK22 { get; set; }
        public Nullable<decimal> CHECK23 { get; set; }
        public Nullable<decimal> CHECK24 { get; set; }
        public Nullable<decimal> CHECK3 { get; set; }
        public Nullable<decimal> CHECK4 { get; set; }
        public Nullable<decimal> CHECK5 { get; set; }
        public Nullable<decimal> CHECK6 { get; set; }
        public Nullable<decimal> CHECK7 { get; set; }
        public Nullable<decimal> CHECK8 { get; set; }
        public Nullable<decimal> CHECK9 { get; set; }
        public string DEPARTM { get; set; }
        public Nullable<decimal> DEPTNO { get; set; }
        public string FAX { get; set; }
        public Nullable<System.DateTime> IDAYDAT1 { get; set; }
        public Nullable<System.DateTime> IDAYDAT2 { get; set; }
        public Nullable<System.DateTime> IDAYDAT3 { get; set; }
        public string IDAYINF1 { get; set; }
        public string IDAYINF2 { get; set; }
        public string IDAYINF3 { get; set; }
        public string IDENT { get; set; }
        public string MODEM { get; set; }
        public string PERINFO1 { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string PHONE4 { get; set; }
        public string PHONE5 { get; set; }
        public string PHONE6 { get; set; }
        public string POSITION { get; set; }
        public string SALESACTION { get; set; }
        public string SALESMAN { get; set; }
        public string SALESORIGIN { get; set; }
        public string SALESSTATUS { get; set; }
        public string SALUTE { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public string TITLE { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
