//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_VERS
    {
        public decimal VERSNO { get; set; }
        public decimal CONO { get; set; }
        public string VNAME { get; set; }
        public Nullable<decimal> DDAY1 { get; set; }
        public Nullable<decimal> DDAY2 { get; set; }
        public Nullable<decimal> DDAY3 { get; set; }
        public Nullable<decimal> DDAY4 { get; set; }
        public Nullable<decimal> DDAY5 { get; set; }
        public Nullable<decimal> DDAY6 { get; set; }
        public Nullable<decimal> DDAY7 { get; set; }
        public string EMAIL { get; set; }
        public string STATE { get; set; }
        public string VADDIT { get; set; }
        public string VADDIT2 { get; set; }
        public string VBEZ { get; set; }
        public string VCSIGN { get; set; }
        public Nullable<decimal> VDISTANZ { get; set; }
        public string VDISTR0 { get; set; }
        public string VDISTR1 { get; set; }
        public string VERSANDI { get; set; }
        public string VLIEFERB { get; set; }
        public string VPLACE { get; set; }
        public string VPOSTCD { get; set; }
        public Nullable<decimal> VPROV0 { get; set; }
        public Nullable<decimal> VPROV1 { get; set; }
        public Nullable<decimal> VRVSSVS { get; set; }
        public string VSPEDIT { get; set; }
        public Nullable<decimal> VSTAT0 { get; set; }
        public Nullable<decimal> VSTAT1 { get; set; }
        public Nullable<decimal> VSTAT2 { get; set; }
        public Nullable<decimal> VSTAT3 { get; set; }
        public string VSTREET { get; set; }
        public string VSTREET2 { get; set; }
        public Nullable<decimal> MINDELIVERYQTYPERC { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
