//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSatisfaction
    {
        public int Satisfaction_Reference { get; set; }
        public Nullable<System.DateTime> Date_Survey_Sent { get; set; }
        public Nullable<System.DateTime> Date_Survey_Back { get; set; }
        public string Period { get; set; }
        public string Improvement_Areas { get; set; }
        public string Comment { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Customer_Reference { get; set; }
        public Nullable<int> Client_Reference { get; set; }
    }
}
