//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Currency
    {
        public string Country_Code { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public Nullable<bool> EC_Member { get; set; }
        public string Currency_Symbol { get; set; }
        public Nullable<bool> Point_Precision { get; set; }
    }
}
