//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomCommand
    {
        public int RecordID { get; set; }
        public string PCName { get; set; }
        public string UserID { get; set; }
        public string CommandType { get; set; }
        public string FormName { get; set; }
        public string MenuCaption { get; set; }
        public string RunCommand { get; set; }
        public string Params { get; set; }
    }
}
