//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultWorkingHr
    {
        public int DefaultWorkingHrsID { get; set; }
        public int Mon_Start { get; set; }
        public int Mon_End { get; set; }
        public int Tue_Start { get; set; }
        public int Tue_End { get; set; }
        public int Wed_Start { get; set; }
        public int Wed_End { get; set; }
        public int Thu_Start { get; set; }
        public int Thu_End { get; set; }
        public int Fri_Start { get; set; }
        public int Fri_End { get; set; }
        public int Sat_Start { get; set; }
        public int Sat_End { get; set; }
        public int Sun_Start { get; set; }
        public int Sun_End { get; set; }
        public string NameStr { get; set; }
        public bool IsDefault { get; set; }
    }
}
