//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int Employee_Details_Reference { get; set; }
        public Nullable<int> Employee_Reference { get; set; }
        public string Notes { get; set; }
        public int Client_Reference { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Last_Modified { get; set; }
        public bool Allow_Locking { get; set; }
        public bool Allow_Unlocking { get; set; }
        public string Lock_Password { get; set; }
        public bool Supplier_Approval { get; set; }
        public bool Customer_Approval { get; set; }
        public byte[] Signature { get; set; }
        public string QuoteEmailSubject { get; set; }
        public string POEmailSubject { get; set; }
        public string OrderAckEmailSubject { get; set; }
        public string COCEmailSubject { get; set; }
        public string QuoteEmailBody { get; set; }
        public string POEmailBody { get; set; }
        public string OrderAckEmailBody { get; set; }
        public string COCEmailBody { get; set; }
        public byte[] signature_Image { get; set; }
        public string InvoiceEmailBody { get; set; }
        public string InvoiceEmailSubject { get; set; }
        public string DeliveryNoteEmailBody { get; set; }
        public string DeliveryNoteEmailSubject { get; set; }
        public string RFQEmailSubject { get; set; }
        public string RFQEmailBody { get; set; }
        public Nullable<bool> CloseOpsOnClockOut { get; set; }
    }
}
