//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAG_UNILOG
    {
        public decimal NO { get; set; }
        public decimal FKNO { get; set; }
        public decimal TYPE { get; set; }
        public decimal ARCHIVED { get; set; }
        public string NAME { get; set; }
        public string MEMO01 { get; set; }
        public Nullable<decimal> VAL01 { get; set; }
        public Nullable<decimal> VAL02 { get; set; }
        public Nullable<decimal> VAL03 { get; set; }
        public Nullable<decimal> VAL04 { get; set; }
        public Nullable<decimal> VAL05 { get; set; }
        public Nullable<decimal> VAL06 { get; set; }
        public Nullable<decimal> VAL07 { get; set; }
        public Nullable<decimal> VAL08 { get; set; }
        public Nullable<decimal> VAL09 { get; set; }
        public Nullable<decimal> VAL10 { get; set; }
        public Nullable<decimal> VAL11 { get; set; }
        public Nullable<decimal> VAL12 { get; set; }
        public Nullable<decimal> VAL13 { get; set; }
        public Nullable<decimal> VAL14 { get; set; }
        public Nullable<decimal> VAL15 { get; set; }
        public Nullable<decimal> VAL16 { get; set; }
        public Nullable<decimal> VAL17 { get; set; }
        public Nullable<decimal> VAL18 { get; set; }
        public Nullable<decimal> VAL19 { get; set; }
        public Nullable<decimal> VAL20 { get; set; }
        public Nullable<decimal> VAL21 { get; set; }
        public Nullable<decimal> VAL22 { get; set; }
        public Nullable<decimal> VAL23 { get; set; }
        public Nullable<decimal> VAL24 { get; set; }
        public Nullable<decimal> VAL25 { get; set; }
        public Nullable<decimal> VAL26 { get; set; }
        public Nullable<decimal> VAL27 { get; set; }
        public Nullable<decimal> VAL28 { get; set; }
        public Nullable<decimal> VAL29 { get; set; }
        public Nullable<decimal> VAL30 { get; set; }
        public Nullable<decimal> VAL31 { get; set; }
        public Nullable<decimal> VAL32 { get; set; }
        public Nullable<decimal> VAL33 { get; set; }
        public Nullable<decimal> VAL34 { get; set; }
        public Nullable<decimal> VAL35 { get; set; }
        public Nullable<decimal> VAL36 { get; set; }
        public Nullable<decimal> VAL37 { get; set; }
        public Nullable<decimal> VAL38 { get; set; }
        public Nullable<decimal> VAL39 { get; set; }
        public Nullable<decimal> VAL40 { get; set; }
        public Nullable<decimal> VAL41 { get; set; }
        public Nullable<decimal> VAL42 { get; set; }
        public Nullable<decimal> VAL43 { get; set; }
        public Nullable<decimal> VAL44 { get; set; }
        public Nullable<decimal> VAL45 { get; set; }
        public Nullable<decimal> VAL46 { get; set; }
        public Nullable<decimal> VAL47 { get; set; }
        public Nullable<decimal> VAL48 { get; set; }
        public Nullable<decimal> VAL49 { get; set; }
        public Nullable<decimal> VAL50 { get; set; }
        public Nullable<decimal> VAL51 { get; set; }
        public Nullable<decimal> VAL52 { get; set; }
        public Nullable<decimal> VAL53 { get; set; }
        public Nullable<decimal> VAL54 { get; set; }
        public Nullable<decimal> VAL55 { get; set; }
        public Nullable<decimal> VAL56 { get; set; }
        public Nullable<decimal> VAL57 { get; set; }
        public Nullable<decimal> VAL58 { get; set; }
        public Nullable<decimal> VAL59 { get; set; }
        public Nullable<decimal> VAL60 { get; set; }
        public Nullable<decimal> VAL61 { get; set; }
        public Nullable<decimal> VAL62 { get; set; }
        public Nullable<decimal> VAL63 { get; set; }
        public Nullable<decimal> VAL64 { get; set; }
        public Nullable<decimal> VAL65 { get; set; }
        public Nullable<decimal> VAL66 { get; set; }
        public Nullable<decimal> VAL67 { get; set; }
        public Nullable<decimal> VAL68 { get; set; }
        public Nullable<decimal> VAL69 { get; set; }
        public Nullable<decimal> VAL70 { get; set; }
        public Nullable<decimal> VAL71 { get; set; }
        public Nullable<decimal> VAL72 { get; set; }
        public Nullable<decimal> VAL73 { get; set; }
        public Nullable<decimal> VAL74 { get; set; }
        public Nullable<decimal> VAL75 { get; set; }
        public Nullable<decimal> VAL76 { get; set; }
        public Nullable<decimal> VAL77 { get; set; }
        public Nullable<decimal> VAL78 { get; set; }
        public Nullable<decimal> VAL79 { get; set; }
        public Nullable<decimal> VAL80 { get; set; }
        public Nullable<decimal> VAL81 { get; set; }
        public Nullable<decimal> VAL82 { get; set; }
        public Nullable<decimal> VAL83 { get; set; }
        public Nullable<decimal> VAL84 { get; set; }
        public Nullable<decimal> VAL85 { get; set; }
        public Nullable<decimal> VAL86 { get; set; }
        public Nullable<decimal> VAL87 { get; set; }
        public Nullable<decimal> VAL88 { get; set; }
        public Nullable<decimal> VAL89 { get; set; }
        public Nullable<decimal> VAL90 { get; set; }
        public Nullable<decimal> VAL91 { get; set; }
        public Nullable<decimal> VAL92 { get; set; }
        public Nullable<decimal> VAL93 { get; set; }
        public Nullable<decimal> VAL94 { get; set; }
        public Nullable<decimal> VAL95 { get; set; }
        public Nullable<decimal> VAL96 { get; set; }
        public Nullable<decimal> VAL97 { get; set; }
        public Nullable<decimal> VAL98 { get; set; }
        public Nullable<decimal> VAL99 { get; set; }
        public string TXT01 { get; set; }
        public string TXT02 { get; set; }
        public string TXT03 { get; set; }
        public string TXT04 { get; set; }
        public string TXT05 { get; set; }
        public string TXT06 { get; set; }
        public string TXT07 { get; set; }
        public string TXT08 { get; set; }
        public string TXT09 { get; set; }
        public string TXT10 { get; set; }
        public Nullable<System.DateTime> DAT01 { get; set; }
        public Nullable<System.DateTime> DAT02 { get; set; }
        public Nullable<System.DateTime> DAT03 { get; set; }
        public Nullable<System.DateTime> DAT04 { get; set; }
        public Nullable<System.DateTime> DAT05 { get; set; }
        public Nullable<System.DateTime> DAT06 { get; set; }
        public Nullable<System.DateTime> DAT07 { get; set; }
        public Nullable<System.DateTime> DAT08 { get; set; }
        public Nullable<System.DateTime> DAT09 { get; set; }
        public Nullable<System.DateTime> DAT10 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public byte[] TSTAMP { get; set; }
    }
}
