//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAG_DETAIL
    {
        public decimal NO { get; set; }
        public decimal FKNO { get; set; }
        public decimal TYP { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> INTERNAL { get; set; }
        public Nullable<decimal> TEMPLATE { get; set; }
        public Nullable<decimal> SHOWONSTARTUP { get; set; }
        public string TEXTLABEL { get; set; }
        public string TEXTTEXT { get; set; }
        public string LANGUAGE { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public Nullable<decimal> VAL01 { get; set; }
        public Nullable<decimal> VAL02 { get; set; }
        public Nullable<decimal> VAL03 { get; set; }
        public Nullable<decimal> VAL04 { get; set; }
        public Nullable<decimal> VAL05 { get; set; }
        public Nullable<decimal> VAL06 { get; set; }
        public Nullable<decimal> VAL07 { get; set; }
        public Nullable<decimal> VAL08 { get; set; }
        public Nullable<decimal> VAL09 { get; set; }
        public Nullable<decimal> VAL10 { get; set; }
        public Nullable<decimal> VAL11 { get; set; }
        public Nullable<decimal> VAL12 { get; set; }
        public Nullable<decimal> VAL13 { get; set; }
        public Nullable<decimal> VAL14 { get; set; }
        public Nullable<decimal> VAL15 { get; set; }
        public Nullable<decimal> VAL16 { get; set; }
        public Nullable<decimal> VAL17 { get; set; }
        public Nullable<decimal> VAL18 { get; set; }
        public Nullable<decimal> VAL19 { get; set; }
        public Nullable<decimal> VAL20 { get; set; }
        public Nullable<decimal> VAL21 { get; set; }
        public Nullable<decimal> VAL22 { get; set; }
        public Nullable<decimal> VAL23 { get; set; }
        public Nullable<decimal> VAL24 { get; set; }
        public Nullable<decimal> VAL25 { get; set; }
        public Nullable<decimal> VAL26 { get; set; }
        public Nullable<decimal> VAL27 { get; set; }
        public Nullable<decimal> VAL28 { get; set; }
        public Nullable<decimal> VAL29 { get; set; }
        public Nullable<decimal> VAL30 { get; set; }
        public Nullable<decimal> VAL31 { get; set; }
        public Nullable<decimal> VAL32 { get; set; }
        public Nullable<decimal> VAL33 { get; set; }
        public Nullable<decimal> VAL34 { get; set; }
        public Nullable<decimal> VAL35 { get; set; }
        public Nullable<decimal> VAL36 { get; set; }
        public Nullable<decimal> VAL37 { get; set; }
        public Nullable<decimal> VAL38 { get; set; }
        public Nullable<decimal> VAL39 { get; set; }
        public Nullable<decimal> VAL40 { get; set; }
        public string TXT01 { get; set; }
        public string TXT02 { get; set; }
        public string TXT03 { get; set; }
        public string TXT04 { get; set; }
        public string TXT05 { get; set; }
        public string TXT06 { get; set; }
        public string TXT07 { get; set; }
        public string TXT08 { get; set; }
        public string TXT09 { get; set; }
        public string TXT10 { get; set; }
        public string TXT11 { get; set; }
        public string TXT12 { get; set; }
        public string TXT13 { get; set; }
        public string TXT14 { get; set; }
        public string TXT15 { get; set; }
        public string TXT16 { get; set; }
        public string TXT17 { get; set; }
        public string TXT18 { get; set; }
        public string TXT19 { get; set; }
        public string TXT20 { get; set; }
        public Nullable<System.DateTime> DAT01 { get; set; }
        public Nullable<System.DateTime> DAT02 { get; set; }
        public Nullable<System.DateTime> DAT03 { get; set; }
        public Nullable<System.DateTime> DAT04 { get; set; }
        public Nullable<System.DateTime> DAT05 { get; set; }
        public Nullable<System.DateTime> DAT06 { get; set; }
        public Nullable<System.DateTime> DAT07 { get; set; }
        public Nullable<System.DateTime> DAT08 { get; set; }
        public Nullable<System.DateTime> DAT09 { get; set; }
        public Nullable<System.DateTime> DAT10 { get; set; }
        public Nullable<System.DateTime> DAT11 { get; set; }
        public Nullable<System.DateTime> DAT12 { get; set; }
        public Nullable<System.DateTime> DAT13 { get; set; }
        public Nullable<System.DateTime> DAT14 { get; set; }
        public Nullable<System.DateTime> DAT15 { get; set; }
        public Nullable<System.DateTime> DAT16 { get; set; }
        public Nullable<System.DateTime> DAT17 { get; set; }
        public Nullable<System.DateTime> DAT18 { get; set; }
        public Nullable<System.DateTime> DAT19 { get; set; }
        public Nullable<System.DateTime> DAT20 { get; set; }
        public byte[] TSTAMP { get; set; }
    }
}
