//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_KASSE
    {
        public decimal NO { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> EINNAHME { get; set; }
        public Nullable<decimal> AUSGABE { get; set; }
        public Nullable<decimal> BESTAND { get; set; }
        public Nullable<decimal> BESTALT { get; set; }
        public string DESCR { get; set; }
        public string BERICHT { get; set; }
        public Nullable<decimal> USTBETRAG { get; set; }
        public string GKONTO { get; set; }
        public string RECHNUNG { get; set; }
        public Nullable<decimal> BELEGNR { get; set; }
        public Nullable<System.DateTime> BELEGDAT { get; set; }
        public Nullable<System.DateTime> BUCHDAT { get; set; }
        public string KST1 { get; set; }
        public string KST2 { get; set; }
        public Nullable<decimal> SKONTO { get; set; }
        public Nullable<decimal> USTSATZ { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
