//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class IS_NUM
    {
        public decimal NO { get; set; }
        public Nullable<decimal> INTNO00 { get; set; }
        public Nullable<decimal> INTNO01 { get; set; }
        public Nullable<decimal> INTNO02 { get; set; }
        public Nullable<decimal> INTNO03 { get; set; }
        public Nullable<decimal> INTNO04 { get; set; }
        public Nullable<decimal> INTNO05 { get; set; }
        public Nullable<decimal> INTNO06 { get; set; }
        public Nullable<decimal> INTNO07 { get; set; }
        public Nullable<decimal> INTNO08 { get; set; }
        public Nullable<decimal> INTNO09 { get; set; }
        public Nullable<decimal> INTNO10 { get; set; }
        public Nullable<decimal> INTNO11 { get; set; }
        public Nullable<decimal> INTNO12 { get; set; }
        public Nullable<decimal> INTNO13 { get; set; }
        public Nullable<decimal> INTNO14 { get; set; }
        public Nullable<decimal> INTNO15 { get; set; }
        public Nullable<decimal> INTNO16 { get; set; }
        public Nullable<decimal> INTNO17 { get; set; }
        public Nullable<decimal> INTNO18 { get; set; }
        public Nullable<decimal> INTNO19 { get; set; }
        public Nullable<decimal> INTNO20 { get; set; }
        public Nullable<decimal> INTNO21 { get; set; }
        public Nullable<decimal> INTNO22 { get; set; }
        public Nullable<decimal> INTNO23 { get; set; }
        public Nullable<decimal> INTNO24 { get; set; }
        public Nullable<decimal> INTNO25 { get; set; }
        public Nullable<decimal> INTNO26 { get; set; }
        public Nullable<decimal> INTNO27 { get; set; }
        public Nullable<decimal> INTNO28 { get; set; }
        public Nullable<decimal> INTNO29 { get; set; }
        public Nullable<decimal> INTNO30 { get; set; }
        public Nullable<decimal> INTNO31 { get; set; }
        public Nullable<decimal> INTNO32 { get; set; }
        public Nullable<decimal> INTNO33 { get; set; }
        public Nullable<decimal> INTNO34 { get; set; }
        public Nullable<decimal> INTNO35 { get; set; }
        public Nullable<decimal> INTNO36 { get; set; }
        public Nullable<decimal> INTNO37 { get; set; }
        public Nullable<decimal> INTNO38 { get; set; }
        public Nullable<decimal> INTNO39 { get; set; }
        public Nullable<decimal> INTNO40 { get; set; }
        public Nullable<decimal> INTNO41 { get; set; }
        public Nullable<decimal> INTNO42 { get; set; }
        public Nullable<decimal> INTNO43 { get; set; }
        public Nullable<decimal> INTNO44 { get; set; }
        public Nullable<decimal> INTNO45 { get; set; }
        public Nullable<decimal> INTNO46 { get; set; }
        public Nullable<decimal> INTNO47 { get; set; }
        public Nullable<decimal> INTNO48 { get; set; }
        public Nullable<decimal> INTNO49 { get; set; }
        public Nullable<decimal> INTNO50 { get; set; }
        public Nullable<decimal> INTNO51 { get; set; }
        public Nullable<decimal> INTNO52 { get; set; }
        public Nullable<decimal> INTNO53 { get; set; }
        public Nullable<decimal> INTNO54 { get; set; }
        public Nullable<decimal> INTNO55 { get; set; }
        public Nullable<decimal> INTNO56 { get; set; }
        public Nullable<decimal> INTNO57 { get; set; }
        public Nullable<decimal> INTNO58 { get; set; }
        public Nullable<decimal> INTNO59 { get; set; }
        public Nullable<decimal> INTNO60 { get; set; }
        public Nullable<decimal> INTNO61 { get; set; }
        public Nullable<decimal> INTNO62 { get; set; }
        public Nullable<decimal> INTNO63 { get; set; }
        public Nullable<decimal> INTNO64 { get; set; }
        public Nullable<decimal> INTNO65 { get; set; }
        public Nullable<decimal> INTNO66 { get; set; }
        public Nullable<decimal> INTNO67 { get; set; }
        public Nullable<decimal> INTNO68 { get; set; }
        public Nullable<decimal> INTNO69 { get; set; }
        public Nullable<decimal> INTNO70 { get; set; }
        public Nullable<decimal> INTNO71 { get; set; }
        public Nullable<decimal> INTNO72 { get; set; }
        public Nullable<decimal> INTNO73 { get; set; }
        public Nullable<decimal> INTNO74 { get; set; }
        public Nullable<decimal> INTNO75 { get; set; }
        public Nullable<decimal> INTNO76 { get; set; }
        public Nullable<decimal> INTNO77 { get; set; }
        public Nullable<decimal> INTNO78 { get; set; }
        public Nullable<decimal> INTNO79 { get; set; }
        public Nullable<decimal> INTNO80 { get; set; }
        public Nullable<decimal> INTNO81 { get; set; }
        public Nullable<decimal> INTNO82 { get; set; }
        public Nullable<decimal> INTNO83 { get; set; }
        public Nullable<decimal> INTNO84 { get; set; }
        public Nullable<decimal> INTNO85 { get; set; }
        public Nullable<decimal> INTNO86 { get; set; }
        public Nullable<decimal> INTNO87 { get; set; }
        public Nullable<decimal> INTNO88 { get; set; }
        public Nullable<decimal> INTNO89 { get; set; }
        public Nullable<decimal> INTNO90 { get; set; }
        public Nullable<decimal> INTNO91 { get; set; }
        public Nullable<decimal> INTNO92 { get; set; }
        public Nullable<decimal> INTNO93 { get; set; }
        public Nullable<decimal> INTNO94 { get; set; }
        public Nullable<decimal> INTNO95 { get; set; }
        public Nullable<decimal> INTNO96 { get; set; }
        public Nullable<decimal> INTNO97 { get; set; }
        public Nullable<decimal> INTNO98 { get; set; }
        public Nullable<decimal> INTNO99 { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
