//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class IS_SETUP
    {
        public decimal NO { get; set; }
        public decimal IDENT { get; set; }
        public string DESC0 { get; set; }
        public string DESC1 { get; set; }
        public string DESC2 { get; set; }
        public string DESC3 { get; set; }
        public Nullable<decimal> STAT0 { get; set; }
        public Nullable<decimal> STAT1 { get; set; }
        public Nullable<decimal> STAT2 { get; set; }
        public Nullable<decimal> STAT3 { get; set; }
        public Nullable<decimal> WERT0 { get; set; }
        public Nullable<decimal> WERT1 { get; set; }
        public Nullable<decimal> WERT2 { get; set; }
        public Nullable<decimal> WERT3 { get; set; }
        public Nullable<decimal> FAKT0 { get; set; }
        public Nullable<decimal> FAKT1 { get; set; }
        public Nullable<decimal> FAKT2 { get; set; }
        public Nullable<decimal> FAKT3 { get; set; }
        public Nullable<decimal> CHECK0 { get; set; }
        public Nullable<decimal> CHECK1 { get; set; }
        public Nullable<decimal> CHECK2 { get; set; }
        public Nullable<decimal> CHECK3 { get; set; }
        public Nullable<decimal> CHECK4 { get; set; }
        public Nullable<decimal> CHECK5 { get; set; }
        public Nullable<decimal> CHECK6 { get; set; }
        public Nullable<decimal> CHECK7 { get; set; }
        public Nullable<decimal> CHECK8 { get; set; }
        public Nullable<decimal> CHECK9 { get; set; }
        public Nullable<decimal> CHECK10 { get; set; }
        public Nullable<decimal> CHECK11 { get; set; }
        public Nullable<decimal> CHECK12 { get; set; }
        public Nullable<decimal> CHECK13 { get; set; }
        public Nullable<decimal> CHECK14 { get; set; }
        public Nullable<decimal> CHECK15 { get; set; }
        public Nullable<decimal> CHECK16 { get; set; }
        public Nullable<decimal> CHECK17 { get; set; }
        public Nullable<decimal> CHECK18 { get; set; }
        public Nullable<decimal> CHECK19 { get; set; }
        public Nullable<decimal> CHECK20 { get; set; }
        public Nullable<decimal> CHECK21 { get; set; }
        public Nullable<decimal> CHECK22 { get; set; }
        public Nullable<decimal> CHECK23 { get; set; }
        public Nullable<decimal> CHECK24 { get; set; }
        public Nullable<decimal> CHECK25 { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
