//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIS_FERTIGUNG
    {
        public string PR_CUSTNO { get; set; }
        public string PR_IDENT { get; set; }
        public string PR_DESCR { get; set; }
        public string PR_DRAWNO { get; set; }
        public string PR_VERSION { get; set; }
        public string PR_ARTNO { get; set; }
        public string PR_COMMNO { get; set; }
        public string PR_INFO2 { get; set; }
        public string PR_RELORD { get; set; }
        public Nullable<System.DateTime> PR_ORDDATE { get; set; }
        public Nullable<decimal> PR_PPARTS { get; set; }
        public Nullable<System.DateTime> PR_DELIVERY { get; set; }
        public string PR_BITMAP { get; set; }
        public Nullable<decimal> PR_EINLAST { get; set; }
        public string PR_NAME { get; set; }
        public string CP_IDENT { get; set; }
        public string CP_DESCR { get; set; }
        public string CP_DRAWNO { get; set; }
        public string CP_VERSION { get; set; }
        public string CP_ARTNO { get; set; }
        public string CP_COMMNO { get; set; }
        public Nullable<System.DateTime> CP_DELIVERY { get; set; }
        public string CP_INFO2 { get; set; }
        public string CP_RELORD { get; set; }
        public Nullable<decimal> CP_PPARTS { get; set; }
        public string CP_BITMAP { get; set; }
        public Nullable<decimal> CP_SEQNUM { get; set; }
        public string CP_NAME { get; set; }
        public string OR_IDENT { get; set; }
        public string OR_DESCR { get; set; }
        public string OR_DRAWNO { get; set; }
        public string OR_VERSION { get; set; }
        public string OR_ARTNO { get; set; }
        public string OR_COMMNO { get; set; }
        public string OR_RELORD { get; set; }
        public Nullable<System.DateTime> OR_DELIVERY { get; set; }
        public string OR_INFO1 { get; set; }
        public string OR_INFO2 { get; set; }
        public string OR_INFO3 { get; set; }
        public Nullable<decimal> OR_PPARTS { get; set; }
        public string OR_BITMAP { get; set; }
        public Nullable<decimal> OR_PREOP { get; set; }
        public Nullable<decimal> OR_SEQNUM { get; set; }
        public string OR_NAME { get; set; }
        public string OP_NAME { get; set; }
        public string OP_DESCR { get; set; }
        public string OP_INFO { get; set; }
        public Nullable<decimal> OP_PTR { get; set; }
        public Nullable<decimal> OP_PTE { get; set; }
        public Nullable<decimal> OP_PPARTS { get; set; }
        public string OP_NCPROG { get; set; }
        public string OP_BITMAP { get; set; }
        public Nullable<decimal> OP_STATUS { get; set; }
        public string OP_WPLACE { get; set; }
        public Nullable<decimal> OP_MATMISSING { get; set; }
        public Nullable<System.DateTime> OP_MATSTIME { get; set; }
        public string OP_MATREMARK { get; set; }
        public Nullable<decimal> OP_PREPMISSING { get; set; }
        public Nullable<System.DateTime> OP_PREPSTIME { get; set; }
        public string OP_PREPREMARK { get; set; }
        public Nullable<decimal> OP_TOOLMISSING { get; set; }
        public Nullable<System.DateTime> OP_TOOLSTIME { get; set; }
        public string OP_TOOLREMARK { get; set; }
        public Nullable<decimal> OP_DIV1MISSING { get; set; }
        public Nullable<System.DateTime> OP_DIV1STIME { get; set; }
        public string OP_DIV1REMARK { get; set; }
        public Nullable<decimal> OP_PTWAIT { get; set; }
        public Nullable<decimal> OP_ATE { get; set; }
        public Nullable<decimal> OP_APARTS { get; set; }
        public Nullable<decimal> OP_OVERLAPPERC { get; set; }
        public Nullable<decimal> OP_OVERLAP { get; set; }
        public Nullable<decimal> OP_SEQNUM { get; set; }
        public string OP_OUTCUSTNO { get; set; }
        public Nullable<decimal> JIS_STATUS1 { get; set; }
        public Nullable<decimal> JIS_STATUS2 { get; set; }
        public Nullable<System.DateTime> JIS_DATUM1 { get; set; }
        public string JIS_DESCR { get; set; }
        public Nullable<decimal> JIS_DEL { get; set; }
        public Nullable<System.DateTime> JIS_CDATE { get; set; }
        public Nullable<System.DateTime> OP_PSTIMEMIN { get; set; }
        public Nullable<System.DateTime> OP_PETIMEMAX { get; set; }
        public string GRPTYP { get; set; }
        public string OP_COLOR { get; set; }
    }
}
