//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIS_ADRESSEN
    {
        public string NAME { get; set; }
        public string ADDITION { get; set; }
        public string CUSTNO { get; set; }
        public string STREET { get; set; }
        public string POSTCODE { get; set; }
        public string PLACE { get; set; }
        public string CNTRYSIGN { get; set; }
        public string CUSTOMERINFO { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string SECPHONE { get; set; }
        public Nullable<decimal> JIS_STATUS1 { get; set; }
        public Nullable<decimal> JIS_STATUS2 { get; set; }
        public Nullable<System.DateTime> JIS_DATUM1 { get; set; }
        public string JIS_DESCR { get; set; }
        public Nullable<decimal> JIS_DEL { get; set; }
        public Nullable<System.DateTime> JIS_CDATE { get; set; }
    }
}
