//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LB_DC
    {
        public decimal LBNO { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> OPNO { get; set; }
        public Nullable<decimal> OPOPNO { get; set; }
        public string ORNAME { get; set; }
        public decimal ORNO { get; set; }
        public Nullable<decimal> OUT { get; set; }
        public Nullable<decimal> ADCCOUNT { get; set; }
        public string ADCMESS { get; set; }
        public Nullable<decimal> ADCSTAT { get; set; }
        public string ADCWORK { get; set; }
        public Nullable<decimal> APARTS { get; set; }
        public Nullable<decimal> ARCHIVE { get; set; }
        public Nullable<decimal> ATE { get; set; }
        public Nullable<decimal> ATP { get; set; }
        public Nullable<decimal> ATR { get; set; }
        public Nullable<decimal> BPARTS { get; set; }
        public Nullable<decimal> BPARTS2 { get; set; }
        public Nullable<decimal> CALTYP { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> ERRNUM { get; set; }
        public Nullable<decimal> EXSTAT { get; set; }
        public Nullable<decimal> FKLBNO { get; set; }
        public Nullable<decimal> FNPK { get; set; }
        public Nullable<decimal> GPARTS { get; set; }
        public Nullable<decimal> INPARTSDBL { get; set; }
        public Nullable<decimal> ISINTERNAL { get; set; }
        public Nullable<decimal> MSGID { get; set; }
        public string MSINFO { get; set; }
        public Nullable<System.DateTime> MSTIME { get; set; }
        public Nullable<decimal> MTIME0 { get; set; }
        public Nullable<decimal> MTIME1 { get; set; }
        public Nullable<decimal> MTIME2 { get; set; }
        public Nullable<decimal> MTIME3 { get; set; }
        public Nullable<decimal> OPMULTIMESSAGEGROUP { get; set; }
        public string PERSNAME { get; set; }
        public Nullable<decimal> PERSNO { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string TERMINAL { get; set; }
        public Nullable<decimal> WPLACE { get; set; }
        public Nullable<decimal> MATCOST { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public byte[] TSTAMP { get; set; }
    }
}
