//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LB_FUNCTION
    {
        public decimal NO { get; set; }
        public Nullable<decimal> FNNO { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> TYP { get; set; }
        public Nullable<decimal> MDCGROUP { get; set; }
        public Nullable<decimal> TIMEUNIT { get; set; }
        public Nullable<decimal> ACTCOUNT { get; set; }
        public Nullable<decimal> TIMECOR { get; set; }
        public Nullable<decimal> MULTIORDER { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> FNGROUP { get; set; }
        public string BARCODE1 { get; set; }
        public string BARCODE2 { get; set; }
        public string BARCODE3 { get; set; }
        public string BARCODE4 { get; set; }
        public string BARCODE5 { get; set; }
        public string BARCODE6 { get; set; }
        public string BARCODE7 { get; set; }
        public string BARCODE8 { get; set; }
        public string BARCODE9 { get; set; }
        public string BARCODE10 { get; set; }
        public Nullable<decimal> DBFIELD { get; set; }
        public Nullable<decimal> FLAG1 { get; set; }
        public Nullable<decimal> FLAG2 { get; set; }
        public Nullable<decimal> FLAG3 { get; set; }
        public Nullable<decimal> FLAG4 { get; set; }
        public Nullable<decimal> FLAG5 { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public string FLDENABLED { get; set; }
        public string FLDVISIBLE { get; set; }
        public string FLDPRESET { get; set; }
        public string PRESET0 { get; set; }
        public string PRESET1 { get; set; }
        public string PRESET2 { get; set; }
        public string PRESET3 { get; set; }
        public string PRESET4 { get; set; }
        public string PRESET5 { get; set; }
        public string PRESET6 { get; set; }
        public string PRESET7 { get; set; }
        public string PRESET8 { get; set; }
        public string PRESET9 { get; set; }
        public string PRESET10 { get; set; }
        public string PRESET11 { get; set; }
        public string PRESET12 { get; set; }
        public string PRESET13 { get; set; }
        public string PRESET14 { get; set; }
        public string PRESET15 { get; set; }
        public string CREATOR { get; set; }
        public string GRIDPRESET { get; set; }
        public string FKKEY { get; set; }
        public Nullable<decimal> OUTCONO { get; set; }
        public string CUSTOMER { get; set; }
        public string TIMEFORMAT { get; set; }
        public Nullable<decimal> SHOWENDED { get; set; }
        public Nullable<decimal> ACTIVATEALL { get; set; }
        public Nullable<decimal> SHOWALL { get; set; }
        public Nullable<decimal> ALLOWNEWOPERATION { get; set; }
        public Nullable<decimal> USEBARCODE { get; set; }
    }
}
