//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceHistory
    {
        public int Maintenance_History_Ref { get; set; }
        public string Record_Type { get; set; }
        public Nullable<System.DateTime> Date_Due { get; set; }
        public Nullable<System.DateTime> Date_Done { get; set; }
        public string Certificate_Number { get; set; }
        public string Peformed_By { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Machine_Reference { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
    }
}
