//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDC_EVENTSTRUCT
    {
        public string PKGUID { get; set; }
        public string FKGUID { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public string XMLDOC { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public string CREATOR { get; set; }
        public Nullable<decimal> FK_FUNCTION { get; set; }
    }
}
