//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominal_codes
    {
        public int NominalCode_Reference { get; set; }
        public string Code { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Type { get; set; }
        public bool Default_for_type { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    }
}
