//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifier
    {
        public int Notifier_Reference { get; set; }
        public string Record_Type { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
        public Nullable<int> Record_Reference { get; set; }
        public string Child_Table { get; set; }
        public Nullable<int> Child_Reference { get; set; }
        public Nullable<int> Active_Tab { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<System.DateTime> Date_Closed { get; set; }
        public Nullable<int> Client_Reference { get; set; }
    }
}
