//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OG_ORGA
    {
        public decimal NO { get; set; }
        public string BITMAP { get; set; }
        public Nullable<System.DateTime> CHTIME { get; set; }
        public string CONAME { get; set; }
        public Nullable<decimal> CONO { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> DATUM0 { get; set; }
        public Nullable<System.DateTime> DATUM1 { get; set; }
        public string DESCR { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> SEQNO0 { get; set; }
        public Nullable<decimal> SEQNO1 { get; set; }
        public Nullable<decimal> SEQNO2 { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
