//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_CNC
    {
        public decimal NO { get; set; }
        public Nullable<decimal> CINDEX { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> OPNO { get; set; }
        public Nullable<decimal> ORNO { get; set; }
        public Nullable<decimal> CPNO { get; set; }
        public Nullable<decimal> PRNO { get; set; }
        public Nullable<decimal> WPNO1 { get; set; }
        public Nullable<decimal> WPNO2 { get; set; }
        public Nullable<decimal> WPNO3 { get; set; }
        public string NCNAME { get; set; }
        public string PPNAME { get; set; }
        public string NCDESC { get; set; }
        public string NCINFO { get; set; }
        public string NCSOURCE { get; set; }
        public string NCINDEX { get; set; }
        public Nullable<System.DateTime> NCDATE { get; set; }
        public Nullable<decimal> FIXTNO { get; set; }
        public string FIXTNAME { get; set; }
        public string FIXTSTOCK { get; set; }
        public string BITMAP { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
