//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_SPC
    {
        public decimal NO { get; set; }
        public Nullable<decimal> NCNO { get; set; }
        public Nullable<decimal> SINDEX { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> OPNO { get; set; }
        public Nullable<decimal> ORNO { get; set; }
        public Nullable<decimal> CPNO { get; set; }
        public Nullable<decimal> PRNO { get; set; }
        public string PPNAME { get; set; }
        public string PPDESC { get; set; }
        public string PPINFO { get; set; }
        public Nullable<decimal> PPTOL1 { get; set; }
        public Nullable<decimal> PPTOL2 { get; set; }
        public Nullable<decimal> PPFREQ { get; set; }
        public Nullable<decimal> PPPRINT { get; set; }
        public Nullable<System.DateTime> PPDATE { get; set; }
        public Nullable<decimal> SPCNO { get; set; }
        public string SPCNAME { get; set; }
        public string SPCSTOCK { get; set; }
        public string BITMAP { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public string CHNAME { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
