//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public string Company_Name { get; set; }
        public string VAT_No { get; set; }
        public bool Barcode_Active { get; set; }
        public bool Auto_Allocation { get; set; }
        public bool Batches_To_Stock { get; set; }
        public bool Component_Copy { get; set; }
        public bool Assembly_Pricing { get; set; }
        public string SystemType { get; set; }
        public bool MassInvoices { get; set; }
        public bool MassDeliveries { get; set; }
        public bool PartNoSorting { get; set; }
        public bool TraceViaCoC { get; set; }
        public bool Discounting { get; set; }
        public string Check_Sum { get; set; }
        public Nullable<int> License_Check_Offset { get; set; }
        public Nullable<bool> RunSecurityModel { get; set; }
        public Nullable<bool> EULA_Accepted { get; set; }
        public string XML_Home { get; set; }
        public string XML_EntityLocation { get; set; }
    }
}
