//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ART
    {
        public decimal ARTNO { get; set; }
        public string ARTDESC { get; set; }
        public string ARTNAME { get; set; }
        public Nullable<decimal> PRONO { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
        public Nullable<decimal> ARTADDR1 { get; set; }
        public Nullable<decimal> ARTADDR2 { get; set; }
        public Nullable<decimal> ARTADDR3 { get; set; }
        public string ARTINF1 { get; set; }
        public string ARTINFO { get; set; }
        public string BITMAPA { get; set; }
        public string BITMAPB { get; set; }
        public Nullable<decimal> BOOKED { get; set; }
        public Nullable<decimal> EINHEIT { get; set; }
        public Nullable<decimal> EKPRICE { get; set; }
        public Nullable<decimal> GRPNO { get; set; }
        public string INADESC { get; set; }
        public Nullable<decimal> INANO { get; set; }
        public Nullable<decimal> INCOMING { get; set; }
        public string INGNAME { get; set; }
        public Nullable<decimal> INGNO { get; set; }
        public Nullable<decimal> INSTATUS { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> LPARTS { get; set; }
        public string MASSEINH { get; set; }
        public Nullable<decimal> MENGE0 { get; set; }
        public Nullable<decimal> MENGE1 { get; set; }
        public Nullable<decimal> MENGE2 { get; set; }
        public Nullable<decimal> MENGE3 { get; set; }
        public Nullable<decimal> MENGE4 { get; set; }
        public Nullable<decimal> MENGE5 { get; set; }
        public Nullable<decimal> MENGE6 { get; set; }
        public Nullable<System.DateTime> ORDDATE { get; set; }
        public Nullable<decimal> ORDERED { get; set; }
        public decimal ORDNO { get; set; }
        public Nullable<System.DateTime> PLANDATE { get; set; }
        public Nullable<decimal> PLATEPARTS { get; set; }
        public Nullable<decimal> PMENGE { get; set; }
        public Nullable<decimal> PPREIS { get; set; }
        public Nullable<decimal> PREIS0 { get; set; }
        public Nullable<decimal> PREIS1 { get; set; }
        public Nullable<decimal> PREIS2 { get; set; }
        public Nullable<decimal> PREIS3 { get; set; }
        public Nullable<decimal> PREIS4 { get; set; }
        public Nullable<decimal> PREIS5 { get; set; }
        public Nullable<decimal> PREIS6 { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public Nullable<decimal> RESERV { get; set; }
        public Nullable<decimal> RLPRICE { get; set; }
        public Nullable<decimal> SUPPLIED { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
