//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CHARGE
    {
        public decimal NO { get; set; }
        public string CHARNO { get; set; }
        public Nullable<decimal> CHTYP { get; set; }
        public Nullable<decimal> EINHST { get; set; }
        public string INFO0 { get; set; }
        public Nullable<decimal> MENGE0 { get; set; }
        public string SALESMAN { get; set; }
        public Nullable<decimal> TYPIND { get; set; }
        public Nullable<System.DateTime> XDATE { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
