//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CALC
    {
        public decimal NO { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CPADMINPERC { get; set; }
        public Nullable<decimal> CPBORDAUX { get; set; }
        public Nullable<decimal> CPBORDDEV { get; set; }
        public Nullable<decimal> CPBORDDEVPROD { get; set; }
        public Nullable<decimal> CPBORDPRIME { get; set; }
        public Nullable<decimal> CPBORDPROD { get; set; }
        public Nullable<decimal> CPBORDSALE { get; set; }
        public Nullable<decimal> CPBORDSPECIAL { get; set; }
        public Nullable<decimal> CPCALCPRICE { get; set; }
        public Nullable<decimal> CPDEVPERC { get; set; }
        public Nullable<decimal> CPDEVPERCRANGE1 { get; set; }
        public Nullable<decimal> CPDEVPERCRANGE2 { get; set; }
        public Nullable<decimal> CPDEVPERCRANGE3 { get; set; }
        public Nullable<decimal> CPDEVPERCRANGE4 { get; set; }
        public Nullable<decimal> CPDEVPERCRANGE5 { get; set; }
        public Nullable<decimal> CPDEVPERCRANGE6 { get; set; }
        public Nullable<decimal> CPDISCOUNT { get; set; }
        public Nullable<decimal> CPDISCPERC { get; set; }
        public Nullable<decimal> CPEXT { get; set; }
        public Nullable<decimal> CPEXTPERC { get; set; }
        public Nullable<decimal> CPFULLAUX { get; set; }
        public Nullable<decimal> CPFULLDEV { get; set; }
        public Nullable<decimal> CPFULLDEVPROD { get; set; }
        public Nullable<decimal> CPFULLPRIME { get; set; }
        public Nullable<decimal> CPFULLPROD { get; set; }
        public Nullable<decimal> CPFULLSALE { get; set; }
        public Nullable<decimal> CPFULLSPECIAL { get; set; }
        public Nullable<decimal> CPGETPRICE { get; set; }
        public Nullable<decimal> CPGETPROV { get; set; }
        public Nullable<decimal> CPMAT { get; set; }
        public Nullable<decimal> CPMATBORD { get; set; }
        public Nullable<decimal> CPMATCOST { get; set; }
        public Nullable<decimal> CPMATFULL { get; set; }
        public Nullable<decimal> CPMATPERC { get; set; }
        public Nullable<decimal> CPPBORD { get; set; }
        public Nullable<decimal> CPPFULL { get; set; }
        public Nullable<decimal> CPPRODPERC { get; set; }
        public Nullable<decimal> CPPROFIT { get; set; }
        public Nullable<decimal> CPPROFITPERC { get; set; }
        public Nullable<decimal> CPPROVISION { get; set; }
        public Nullable<decimal> CPPROVISPERC { get; set; }
        public string CPREMARK { get; set; }
        public Nullable<decimal> CPSALEPERC { get; set; }
        public Nullable<decimal> CPSPECIALPERC { get; set; }
        public Nullable<decimal> CPSUPPLY { get; set; }
        public Nullable<decimal> CPSUPPLYPERC { get; set; }
        public Nullable<decimal> CPOUT { get; set; }
        public Nullable<decimal> CRADMINPERC { get; set; }
        public Nullable<decimal> CRBORDAUX { get; set; }
        public Nullable<decimal> CRBORDDEV { get; set; }
        public Nullable<decimal> CRBORDDEVPROD { get; set; }
        public Nullable<decimal> CRBORDPRIME { get; set; }
        public Nullable<decimal> CRBORDPROD { get; set; }
        public Nullable<decimal> CRBORDSALE { get; set; }
        public Nullable<decimal> CRBORDSPECIAL { get; set; }
        public Nullable<decimal> CRCALCPRICE { get; set; }
        public Nullable<decimal> CRDISCOUNT { get; set; }
        public Nullable<decimal> CRDEVPERC { get; set; }
        public Nullable<decimal> CRDEVPERCRANGE1 { get; set; }
        public Nullable<decimal> CRDEVPERCRANGE2 { get; set; }
        public Nullable<decimal> CRDEVPERCRANGE3 { get; set; }
        public Nullable<decimal> CRDEVPERCRANGE4 { get; set; }
        public Nullable<decimal> CRDEVPERCRANGE5 { get; set; }
        public Nullable<decimal> CRDEVPERCRANGE6 { get; set; }
        public Nullable<decimal> CRDISCPERC { get; set; }
        public Nullable<decimal> CREXT { get; set; }
        public Nullable<decimal> CREXTPERC { get; set; }
        public Nullable<decimal> CRFULLAUX { get; set; }
        public Nullable<decimal> CRFULLDEV { get; set; }
        public Nullable<decimal> CRFULLDEVPROD { get; set; }
        public Nullable<decimal> CRFULLPRIME { get; set; }
        public Nullable<decimal> CRFULLPROD { get; set; }
        public Nullable<decimal> CRFULLSALE { get; set; }
        public Nullable<decimal> CRFULLSPECIAL { get; set; }
        public Nullable<decimal> CRGETPRICE { get; set; }
        public Nullable<decimal> CRGETPROV { get; set; }
        public Nullable<decimal> CRMAT { get; set; }
        public Nullable<decimal> CRMATBORD { get; set; }
        public Nullable<decimal> CRMATCOST { get; set; }
        public Nullable<decimal> CRMATFULL { get; set; }
        public Nullable<decimal> CRMATPERC { get; set; }
        public Nullable<decimal> CRPBORD { get; set; }
        public Nullable<decimal> CRPFULL { get; set; }
        public Nullable<decimal> CRPRODPERC { get; set; }
        public Nullable<decimal> CRPROFIT { get; set; }
        public Nullable<decimal> CRPROFITPERC { get; set; }
        public Nullable<decimal> CRPROVISION { get; set; }
        public Nullable<decimal> CRPROVISPERC { get; set; }
        public string CRREMARK { get; set; }
        public Nullable<decimal> CRSALEPERC { get; set; }
        public Nullable<decimal> CRSPECIALPERC { get; set; }
        public Nullable<decimal> CRSUPPLY { get; set; }
        public Nullable<decimal> CRSUPPLYPERC { get; set; }
        public Nullable<decimal> CROUT { get; set; }
        public Nullable<decimal> DELQUOTATION { get; set; }
        public Nullable<decimal> DELQUOTATIONINCLUDED { get; set; }
        public Nullable<decimal> TGCOST { get; set; }
        public Nullable<decimal> TGREADY { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
