//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_FRAG
    {
        public string PKGUID { get; set; }
        public Nullable<decimal> ORNO { get; set; }
        public Nullable<decimal> OPNO { get; set; }
        public Nullable<System.DateTime> STIME { get; set; }
        public Nullable<decimal> STARTSEC { get; set; }
        public Nullable<System.DateTime> ETIME { get; set; }
        public Nullable<decimal> ENDSEC { get; set; }
        public Nullable<decimal> PPARTS { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
        public Nullable<decimal> PWPLACE { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
