//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_PROJ
    {
        public decimal NO { get; set; }
        public Nullable<decimal> MUSTERNO { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public string IDENT { get; set; }
        public Nullable<decimal> PPARTS { get; set; }
        public Nullable<decimal> SEQNO { get; set; }
        public Nullable<decimal> SOURCE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> EINLAST { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public string ADTEXT { get; set; }
        public string ARTNO { get; set; }
        public Nullable<decimal> ASSART { get; set; }
        public Nullable<decimal> ASSARTNO { get; set; }
        public Nullable<decimal> BESTMENGE { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> CFLAG { get; set; }
        public Nullable<System.DateTime> CHTIME { get; set; }
        public Nullable<decimal> CLEARANCE { get; set; }
        public string COMMNO { get; set; }
        public Nullable<decimal> CONO { get; set; }
        public string COSTDEPT { get; set; }
        public Nullable<decimal> CPGETP { get; set; }
        public Nullable<decimal> CRGETP { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> DATUM0 { get; set; }
        public Nullable<System.DateTime> DATUM1 { get; set; }
        public Nullable<System.DateTime> DATUM2 { get; set; }
        public Nullable<System.DateTime> DATUM3 { get; set; }
        public Nullable<System.DateTime> DELIVERY { get; set; }
        public string DRAWIND { get; set; }
        public string DRAWNO { get; set; }
        public Nullable<decimal> EINHEIT { get; set; }
        public Nullable<decimal> ERROR { get; set; }
        public Nullable<System.DateTime> ETIME { get; set; }
        public Nullable<decimal> FAKTOR1 { get; set; }
        public Nullable<decimal> FAKTOR2 { get; set; }
        public Nullable<decimal> FAKTOR3 { get; set; }
        public string FORMNA { get; set; }
        public string FORMVA { get; set; }
        public string GKN01 { get; set; }
        public string GKN02 { get; set; }
        public Nullable<decimal> GRPNO { get; set; }
        public string HPGLFILE { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public Nullable<decimal> KCONO { get; set; }
        public string MASSEINH { get; set; }
        public Nullable<decimal> MDIM1 { get; set; }
        public Nullable<decimal> MDIM2 { get; set; }
        public Nullable<decimal> MDIM3 { get; set; }
        public Nullable<decimal> MENGE1 { get; set; }
        public Nullable<decimal> MENGE2 { get; set; }
        public Nullable<decimal> MENGE3 { get; set; }
        public Nullable<decimal> MENGE4 { get; set; }
        public Nullable<decimal> MENGE5 { get; set; }
        public Nullable<decimal> MENGE6 { get; set; }
        public Nullable<decimal> MENGE7 { get; set; }
        public Nullable<decimal> MENGE8 { get; set; }
        public Nullable<decimal> MINPRICE { get; set; }
        public Nullable<decimal> MWEIG1 { get; set; }
        public Nullable<decimal> MWEIG2 { get; set; }
        public Nullable<decimal> MWEIG3 { get; set; }
        public Nullable<decimal> OGNO { get; set; }
        public Nullable<decimal> OGNO1 { get; set; }
        public Nullable<decimal> OGNO2 { get; set; }
        public Nullable<decimal> OGNO3 { get; set; }
        public Nullable<decimal> OGNO4 { get; set; }
        public Nullable<System.DateTime> ORDDATE { get; set; }
        public string ORDOC0 { get; set; }
        public string ORDOC1 { get; set; }
        public string ORDOC2 { get; set; }
        public string ORGANAME { get; set; }
        public Nullable<decimal> ORGANO { get; set; }
        public Nullable<decimal> ORPRT0 { get; set; }
        public Nullable<decimal> ORPRT1 { get; set; }
        public Nullable<decimal> ORPRT2 { get; set; }
        public Nullable<decimal> ORSETP0 { get; set; }
        public Nullable<decimal> ORSETP1 { get; set; }
        public Nullable<decimal> ORSETP2 { get; set; }
        public Nullable<decimal> ORSETP3 { get; set; }
        public Nullable<decimal> OVERLAP { get; set; }
        public Nullable<decimal> OVERLAPDIFF { get; set; }
        public Nullable<decimal> OVERLAPPERC { get; set; }
        public Nullable<System.DateTime> PETIMEMAX { get; set; }
        public Nullable<System.DateTime> PETIMEMIN { get; set; }
        public Nullable<decimal> POSTNO { get; set; }
        public Nullable<decimal> POSTOP { get; set; }
        public Nullable<decimal> PREIS1 { get; set; }
        public Nullable<decimal> PREIS2 { get; set; }
        public Nullable<decimal> PREIS3 { get; set; }
        public Nullable<decimal> PREIS4 { get; set; }
        public Nullable<decimal> PREIS5 { get; set; }
        public Nullable<decimal> PREIS6 { get; set; }
        public Nullable<decimal> PREIS7 { get; set; }
        public Nullable<decimal> PREIS8 { get; set; }
        public Nullable<decimal> PREJECTS { get; set; }
        public Nullable<decimal> PRENO { get; set; }
        public Nullable<decimal> PREOP { get; set; }
        public string PRICEINFO { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public Nullable<decimal> PRIO { get; set; }
        public Nullable<decimal> PROBLEM { get; set; }
        public Nullable<decimal> PRODUCTIONSTATE { get; set; }
        public Nullable<decimal> PRONO { get; set; }
        public Nullable<System.DateTime> PSTIMEMAX { get; set; }
        public Nullable<System.DateTime> PSTIMEMIN { get; set; }
        public Nullable<System.DateTime> PSTIMEMIN2 { get; set; }
        public Nullable<decimal> PTE { get; set; }
        public Nullable<decimal> PTG { get; set; }
        public Nullable<decimal> PTH { get; set; }
        public Nullable<decimal> PTR { get; set; }
        public Nullable<decimal> PTRA { get; set; }
        public Nullable<decimal> PTTRANS { get; set; }
        public Nullable<decimal> PTWAIT { get; set; }
        public Nullable<decimal> REBOOKED { get; set; }
        public Nullable<decimal> RELOPCNT { get; set; }
        public string RELORD { get; set; }
        public Nullable<decimal> REPTIME { get; set; }
        public Nullable<decimal> SCNO { get; set; }
        public Nullable<decimal> SDEVPROD1 { get; set; }
        public Nullable<decimal> SDEVPROD2 { get; set; }
        public Nullable<decimal> SDEVPROD3 { get; set; }
        public Nullable<decimal> SDEVPROD4 { get; set; }
        public Nullable<decimal> SDEVPROD5 { get; set; }
        public Nullable<decimal> SDEVPROD6 { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
        public Nullable<decimal> SPECIAL { get; set; }
        public Nullable<decimal> SPERC0 { get; set; }
        public Nullable<decimal> SPERC1 { get; set; }
        public Nullable<decimal> SPERC2 { get; set; }
        public Nullable<decimal> SPERC3 { get; set; }
        public Nullable<decimal> SPERC4 { get; set; }
        public Nullable<decimal> SPERC5 { get; set; }
        public Nullable<System.DateTime> STIME { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string USR { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public byte[] TSTAMP { get; set; }
    }
}
