//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_SERIAL
    {
        public decimal NO { get; set; }
        public Nullable<decimal> FKNO { get; set; }
        public Nullable<decimal> FKTYPE { get; set; }
        public Nullable<decimal> FKPKNO { get; set; }
        public string SN { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> BOOKED { get; set; }
        public string CHIPID { get; set; }
        public Nullable<decimal> CURRENTOP { get; set; }
        public Nullable<decimal> CURRENTOPSTATE { get; set; }
        public Nullable<decimal> DELIVERED { get; set; }
        public Nullable<decimal> FKPONO { get; set; }
        public Nullable<decimal> OFFSETC { get; set; }
        public Nullable<decimal> OFFSETX { get; set; }
        public Nullable<decimal> OFFSETY { get; set; }
        public Nullable<decimal> OFFSETZ { get; set; }
        public string PALLETID { get; set; }
        public string PROJNAME { get; set; }
        public Nullable<decimal> PSTATE { get; set; }
        public Nullable<decimal> QSTATE { get; set; }
        public Nullable<decimal> SCRAP { get; set; }
        public string SCRAPDESC { get; set; }
        public Nullable<decimal> SERIALSTATUS { get; set; }
        public Nullable<decimal> SERIALTYPE { get; set; }
        public Nullable<decimal> SNACOUNTER { get; set; }
        public Nullable<decimal> SNCOUNTER { get; set; }
        public string STOCKLOCATION { get; set; }
        public Nullable<decimal> USERFLAG { get; set; }
        public string USERTEXT { get; set; }
        public Nullable<decimal> WORKSTEP2 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public byte[] TSTAMP { get; set; }
    }
}
