//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Events
    {
        public int Record_Ref { get; set; }
        public int Order_Reference { get; set; }
        public string Record_Type { get; set; }
        public Nullable<int> Item_Reference { get; set; }
        public string Recorded_By { get; set; }
        public string Contact_Name { get; set; }
        public string Comment { get; set; }
        public int Revision { get; set; }
        public string Order_Type { get; set; }
        public Nullable<System.DateTime> Revision_date { get; set; }
        public Nullable<bool> Acknowledged { get; set; }
        public Nullable<System.DateTime> Ack_Date { get; set; }
        public Nullable<System.DateTime> Promise_Date { get; set; }
        public string Order_Reference_suffix { get; set; }
    }
}
