//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_ARTHIS
    {
        public decimal NO { get; set; }
        public decimal ARTNO { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> CONO { get; set; }
        public Nullable<decimal> PREIS1 { get; set; }
        public Nullable<decimal> PREIS2 { get; set; }
        public Nullable<decimal> PREIS3 { get; set; }
        public Nullable<decimal> PREIS4 { get; set; }
        public Nullable<decimal> PREIS5 { get; set; }
        public Nullable<decimal> PREIS6 { get; set; }
        public Nullable<decimal> MENGE1 { get; set; }
        public Nullable<decimal> MENGE2 { get; set; }
        public Nullable<decimal> MENGE3 { get; set; }
        public Nullable<decimal> MENGE4 { get; set; }
        public Nullable<decimal> MENGE5 { get; set; }
        public Nullable<decimal> MENGE6 { get; set; }
        public Nullable<decimal> EINHEIT { get; set; }
        public Nullable<decimal> FAKTOR { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public Nullable<decimal> FKPLNO { get; set; }
        public Nullable<decimal> NETPRICE1 { get; set; }
        public Nullable<decimal> NETPRICE2 { get; set; }
        public Nullable<decimal> NETPRICE3 { get; set; }
        public Nullable<decimal> NETPRICE4 { get; set; }
        public Nullable<decimal> NETPRICE5 { get; set; }
        public Nullable<decimal> NETPRICE6 { get; set; }
        public Nullable<decimal> DISCOUNT1 { get; set; }
        public Nullable<decimal> DISCOUNT2 { get; set; }
        public Nullable<decimal> DISCOUNT3 { get; set; }
        public Nullable<decimal> DISCOUNT4 { get; set; }
        public Nullable<decimal> DISCOUNT5 { get; set; }
        public Nullable<decimal> DISCOUNT6 { get; set; }
        public Nullable<decimal> PADDITION1 { get; set; }
        public Nullable<decimal> PADDITION2 { get; set; }
        public Nullable<decimal> PADDITION3 { get; set; }
        public Nullable<decimal> PADDITION4 { get; set; }
        public Nullable<decimal> PADDITION5 { get; set; }
        public Nullable<decimal> PADDITION6 { get; set; }
        public Nullable<decimal> MINPRICE { get; set; }
        public Nullable<decimal> SETUPCOSTS { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> FORBIDADDRESSDISCOUNT { get; set; }
    }
}
