//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_ARTGRP
    {
        public decimal GRPNO { get; set; }
        public string GRPNAME { get; set; }
        public Nullable<decimal> ACCOUNT0 { get; set; }
        public Nullable<decimal> ACCOUNT1 { get; set; }
        public Nullable<decimal> ACCOUNT2 { get; set; }
        public Nullable<decimal> ACCOUNT3 { get; set; }
        public Nullable<decimal> ADDRNO0 { get; set; }
        public Nullable<decimal> ADDRNO1 { get; set; }
        public Nullable<decimal> ADDRNO2 { get; set; }
        public Nullable<decimal> ADDRNO3 { get; set; }
        public Nullable<decimal> ADDRNO4 { get; set; }
        public Nullable<decimal> ADDRNO5 { get; set; }
        public string AGRINF1 { get; set; }
        public string AGRINF2 { get; set; }
        public Nullable<decimal> ALAGER0 { get; set; }
        public Nullable<decimal> ALAGER1 { get; set; }
        public Nullable<decimal> ALAGER2 { get; set; }
        public Nullable<decimal> ALAGER3 { get; set; }
        public Nullable<decimal> ALAGER4 { get; set; }
        public Nullable<decimal> ALAGER5 { get; set; }
        public string ALAGERN { get; set; }
        public Nullable<decimal> APLACEI { get; set; }
        public string ARTDOC0 { get; set; }
        public string ARTDOC1 { get; set; }
        public string ARTDOC2 { get; set; }
        public Nullable<decimal> ARTPRT0 { get; set; }
        public Nullable<decimal> ARTPRT1 { get; set; }
        public Nullable<decimal> ARTPRT2 { get; set; }
        public Nullable<decimal> BESTM0 { get; set; }
        public Nullable<decimal> BESTM1 { get; set; }
        public Nullable<decimal> BESTM2 { get; set; }
        public string BITMAPA { get; set; }
        public string BITMAPB { get; set; }
        public Nullable<decimal> EINHEIT { get; set; }
        public Nullable<decimal> EINKAUF0 { get; set; }
        public Nullable<decimal> EINKAUF1 { get; set; }
        public Nullable<decimal> EINKAUF2 { get; set; }
        public Nullable<decimal> EINKAUF3 { get; set; }
        public Nullable<decimal> EINKAUF4 { get; set; }
        public Nullable<decimal> EINKAUF5 { get; set; }
        public Nullable<decimal> EKPERC { get; set; }
        public Nullable<decimal> EKPREIS { get; set; }
        public Nullable<decimal> EPREIS0 { get; set; }
        public Nullable<decimal> EPREIS1 { get; set; }
        public Nullable<decimal> EPREIS2 { get; set; }
        public Nullable<decimal> EPREIS3 { get; set; }
        public Nullable<decimal> EPREIS4 { get; set; }
        public Nullable<decimal> EPREIS5 { get; set; }
        public Nullable<decimal> EPROZ0 { get; set; }
        public Nullable<decimal> EPROZ1 { get; set; }
        public Nullable<decimal> EPROZ2 { get; set; }
        public Nullable<decimal> EPROZ3 { get; set; }
        public Nullable<decimal> EPROZ4 { get; set; }
        public Nullable<decimal> EPROZ5 { get; set; }
        public Nullable<decimal> FAKTOR1 { get; set; }
        public Nullable<decimal> FAKTOR2 { get; set; }
        public Nullable<decimal> FAKTOR3 { get; set; }
        public string MASSEINH { get; set; }
        public Nullable<decimal> MDIM1 { get; set; }
        public Nullable<decimal> MDIM2 { get; set; }
        public Nullable<decimal> MDIM3 { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public Nullable<decimal> MENGE5 { get; set; }
        public Nullable<decimal> MENGE6 { get; set; }
        public Nullable<decimal> MIDENT1 { get; set; }
        public Nullable<decimal> MIDENT2 { get; set; }
        public Nullable<decimal> MIDENT3 { get; set; }
        public Nullable<decimal> MINBE3 { get; set; }
        public Nullable<decimal> MINBE4 { get; set; }
        public Nullable<decimal> MINBE5 { get; set; }
        public Nullable<decimal> MWEIG1 { get; set; }
        public Nullable<decimal> MWEIG2 { get; set; }
        public Nullable<decimal> MWEIG3 { get; set; }
        public Nullable<decimal> PREIS5 { get; set; }
        public Nullable<decimal> PREIS6 { get; set; }
        public Nullable<decimal> VKPERC { get; set; }
        public Nullable<decimal> VKPREIS { get; set; }
        public Nullable<decimal> VPREIS0 { get; set; }
        public Nullable<decimal> VPREIS1 { get; set; }
        public Nullable<decimal> VPREIS2 { get; set; }
        public Nullable<decimal> VPREIS3 { get; set; }
        public Nullable<decimal> VPREIS4 { get; set; }
        public Nullable<decimal> VPREIS5 { get; set; }
        public Nullable<decimal> VPROZ0 { get; set; }
        public Nullable<decimal> VPROZ1 { get; set; }
        public Nullable<decimal> VPROZ2 { get; set; }
        public Nullable<decimal> VPROZ3 { get; set; }
        public Nullable<decimal> VPROZ4 { get; set; }
        public Nullable<decimal> VPROZ5 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
