//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_ARTLIEF
    {
        public decimal ARTLNO { get; set; }
        public decimal ARTNO { get; set; }
        public string LARTNO { get; set; }
        public decimal CONO { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> DISCOUNT1 { get; set; }
        public Nullable<decimal> DISCOUNT2 { get; set; }
        public Nullable<decimal> DISCOUNT3 { get; set; }
        public Nullable<decimal> DISCOUNT4 { get; set; }
        public Nullable<decimal> DISCOUNT5 { get; set; }
        public Nullable<decimal> DISCOUNT6 { get; set; }
        public Nullable<decimal> DLIEF1 { get; set; }
        public Nullable<decimal> DLIEF2 { get; set; }
        public Nullable<decimal> EKMENGE1 { get; set; }
        public Nullable<decimal> EKMENGE2 { get; set; }
        public Nullable<decimal> EKMENGE3 { get; set; }
        public Nullable<decimal> EKMENGE4 { get; set; }
        public Nullable<decimal> EKMENGE5 { get; set; }
        public Nullable<decimal> EKMENGE6 { get; set; }
        public Nullable<decimal> EKPREIS1 { get; set; }
        public Nullable<decimal> EKPREIS2 { get; set; }
        public Nullable<decimal> EKPREIS3 { get; set; }
        public Nullable<decimal> EKPREIS4 { get; set; }
        public Nullable<decimal> EKPREIS5 { get; set; }
        public Nullable<decimal> EKPREIS6 { get; set; }
        public Nullable<System.DateTime> FDATE1 { get; set; }
        public Nullable<System.DateTime> FDATE2 { get; set; }
        public Nullable<System.DateTime> FDATE3 { get; set; }
        public Nullable<System.DateTime> FDATE4 { get; set; }
        public Nullable<System.DateTime> FDATE5 { get; set; }
        public Nullable<System.DateTime> FDATE6 { get; set; }
        public Nullable<decimal> FDOUBLE1 { get; set; }
        public Nullable<decimal> FDOUBLE2 { get; set; }
        public Nullable<decimal> FDOUBLE3 { get; set; }
        public Nullable<decimal> FDOUBLE4 { get; set; }
        public Nullable<decimal> FDOUBLE5 { get; set; }
        public Nullable<decimal> FDOUBLE6 { get; set; }
        public Nullable<decimal> IDENT { get; set; }
        public string INFO { get; set; }
        public Nullable<decimal> MIN1 { get; set; }
        public Nullable<decimal> MIN2 { get; set; }
        public Nullable<decimal> MIN3 { get; set; }
        public Nullable<decimal> MINPRICE { get; set; }
        public Nullable<decimal> NETPRICE1 { get; set; }
        public Nullable<decimal> NETPRICE2 { get; set; }
        public Nullable<decimal> NETPRICE3 { get; set; }
        public Nullable<decimal> NETPRICE4 { get; set; }
        public Nullable<decimal> NETPRICE5 { get; set; }
        public Nullable<decimal> NETPRICE6 { get; set; }
        public Nullable<decimal> PADDITION1 { get; set; }
        public Nullable<decimal> PADDITION2 { get; set; }
        public Nullable<decimal> PADDITION3 { get; set; }
        public Nullable<decimal> PADDITION4 { get; set; }
        public Nullable<decimal> PADDITION5 { get; set; }
        public Nullable<decimal> PADDITION6 { get; set; }
        public Nullable<decimal> SETUPCOSTS { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> STATUS1 { get; set; }
        public Nullable<decimal> STATUS2 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
