//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_FIBU
    {
        public decimal FIBNO { get; set; }
        public Nullable<System.DateTime> DATUM { get; set; }
        public string DESCR { get; set; }
        public Nullable<System.DateTime> EXPORTDATE { get; set; }
        public string KONTO { get; set; }
        public Nullable<decimal> MAXWVNO { get; set; }
        public decimal PANO { get; set; }
        public Nullable<System.DateTime> PAYDATE0 { get; set; }
        public Nullable<System.DateTime> PAYDATE1 { get; set; }
        public string PAYINF0 { get; set; }
        public string PAYINF1 { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> TBRUTTO { get; set; }
        public Nullable<decimal> WVNO { get; set; }
        public string ORGCURRENCY { get; set; }
        public Nullable<decimal> ORGEXCHANGERATE { get; set; }
        public Nullable<decimal> ORGECTYPE { get; set; }
        public Nullable<decimal> ORGAMOUNT { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
    }
}
