//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_FIT
    {
        public decimal NO { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string PAPERNUMBER { get; set; }
        public string PROJECTNUMBER { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> GROSS { get; set; }
        public Nullable<decimal> NET { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> VAT_PERCENT { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> GROSS_FOREIGN { get; set; }
        public Nullable<decimal> NET_FOREIGN { get; set; }
        public Nullable<decimal> VAT_FOREIGN { get; set; }
        public Nullable<decimal> VAT_PERCENT_FOR { get; set; }
        public string CURRENCY_FOREIGN { get; set; }
        public string ACCOUNT1 { get; set; }
        public string ACCOUNT2 { get; set; }
        public string CUSTNO { get; set; }
        public string VATID { get; set; }
        public Nullable<System.DateTime> DATEOFINVOICE { get; set; }
        public Nullable<System.DateTime> DATEOFDELIVERY { get; set; }
        public string LATESTTIMETOPAY { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string ORDERNUMBER { get; set; }
        public Nullable<System.DateTime> DATE0 { get; set; }
        public Nullable<System.DateTime> DATE1 { get; set; }
        public string INF0 { get; set; }
        public string INF1 { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> PAY_GROSS { get; set; }
        public Nullable<decimal> PAY_NET { get; set; }
        public Nullable<decimal> PAY_VAT { get; set; }
        public string PAY_CURRENCY { get; set; }
        public Nullable<decimal> PAY_GROSS_FOR { get; set; }
        public Nullable<decimal> PAY_NET_FOR { get; set; }
        public Nullable<decimal> PAY_VAT_FOR { get; set; }
        public string PAY_CURRENCY_FOR { get; set; }
        public string ORDERNO { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
    }
}
