//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_PACKAGING
    {
        public decimal PKNO { get; set; }
        public Nullable<decimal> FKNO { get; set; }
        public Nullable<decimal> GROUPPRIORITY { get; set; }
        public string GROUPNAME { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
        public Nullable<decimal> FKNOPA { get; set; }
        public Nullable<decimal> FILLQUANTITY { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> SELL { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> PRINTQUANTITY { get; set; }
        public Nullable<decimal> PARAMIDENT { get; set; }
        public Nullable<decimal> PRINTQTYABS { get; set; }
    }
}
