//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_POSIT
    {
        public decimal PONO { get; set; }
        public Nullable<decimal> PANO { get; set; }
        public decimal POSNO { get; set; }
        public string POSART { get; set; }
        public string POSTXTL { get; set; }
        public decimal AUSGNO { get; set; }
        public decimal VORGNO { get; set; }
        public Nullable<decimal> ALTAUSGNO { get; set; }
        public Nullable<decimal> ALTIDENT { get; set; }
        public Nullable<decimal> ALTVORGNO { get; set; }
        public Nullable<decimal> AMOUNTEXPORT { get; set; }
        public Nullable<System.DateTime> APOSDAT { get; set; }
        public Nullable<decimal> BOOKSTATUS { get; set; }
        public Nullable<decimal> CALSTATUS { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> DISCOUNTABS { get; set; }
        public Nullable<decimal> EINHEIT { get; set; }
        public Nullable<decimal> EPREIS { get; set; }
        public Nullable<decimal> EPREIS1 { get; set; }
        public Nullable<decimal> FREMDWAEHRUNG { get; set; }
        public Nullable<decimal> GPREIS { get; set; }
        public Nullable<decimal> GPREIS1 { get; set; }
        public Nullable<decimal> GRUNDPREIS { get; set; }
        public Nullable<decimal> INCOMING { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> LINKFK { get; set; }
        public string MASSEINH { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MGRPNAME { get; set; }
        public Nullable<decimal> OLDPOS { get; set; }
        public Nullable<decimal> OLDPOS2 { get; set; }
        public Nullable<decimal> OLDPOS3 { get; set; }
        public Nullable<decimal> ORDERED { get; set; }
        public Nullable<decimal> PACKAGINGFK { get; set; }
        public Nullable<decimal> PACKAGINGSELL { get; set; }
        public Nullable<decimal> PACKAGINGUNIT { get; set; }
        public Nullable<decimal> PAYPERMISSION { get; set; }
        public Nullable<System.DateTime> PETIMEMAX { get; set; }
        public Nullable<decimal> PLNO { get; set; }
        public Nullable<System.DateTime> POSDAT { get; set; }
        public string POSDOC0 { get; set; }
        public string POSDOC1 { get; set; }
        public string POSDOC2 { get; set; }
        public string POSDOC3 { get; set; }
        public Nullable<decimal> POSIDENT { get; set; }
        public string POSIDNAM { get; set; }
        public Nullable<decimal> POSIDNO { get; set; }
        public string POSINF { get; set; }
        public Nullable<decimal> POSLIEF0 { get; set; }
        public Nullable<decimal> POSLIEF1 { get; set; }
        public Nullable<decimal> POSLIEF2 { get; set; }
        public Nullable<decimal> POSLIEF3 { get; set; }
        public Nullable<decimal> POSLIEF4 { get; set; }
        public Nullable<decimal> POSLIEF5 { get; set; }
        public Nullable<decimal> POSPRT0 { get; set; }
        public Nullable<decimal> POSPRT1 { get; set; }
        public Nullable<decimal> POSPRT2 { get; set; }
        public string POSTART { get; set; }
        public string POSTEXT { get; set; }
        public string POSTNAME { get; set; }
        public Nullable<decimal> POSTNO { get; set; }
        public Nullable<decimal> POSTYP { get; set; }
        public Nullable<System.DateTime> RPOSDAT { get; set; }
        public Nullable<decimal> PRINTQUANTITY { get; set; }
        public Nullable<decimal> PROJECT { get; set; }
        public string PROJNAME { get; set; }
        public Nullable<System.DateTime> PSTIMEMIN { get; set; }
        public Nullable<decimal> PTYP { get; set; }
        public Nullable<decimal> RABATT { get; set; }
        public string REVENUEACC { get; set; }
        public Nullable<decimal> SEPARATESETUPCOSTS { get; set; }
        public Nullable<decimal> VERTID { get; set; }
        public string VERTRNAME { get; set; }
        public string VKCNTRYSIGN { get; set; }
        public string VKCNTRYSIGNF { get; set; }
        public Nullable<decimal> VKUMRECHFAKT { get; set; }
        public Nullable<decimal> VKUMRECHFAKTF { get; set; }
        public string VKWAEHRUNG { get; set; }
        public string VKWAEHRUNGF { get; set; }
        public Nullable<decimal> VPROV { get; set; }
        public Nullable<decimal> VPROVABS { get; set; }
        public Nullable<decimal> VRABATT { get; set; }
        public Nullable<decimal> VRABATTABS { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
