//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_STLB
    {
        public decimal LBNO { get; set; }
        public decimal ARTNO { get; set; }
        public string ARTDESC { get; set; }
        public string ARTNAME { get; set; }
        public string CHARNO { get; set; }
        public Nullable<decimal> ORDNO { get; set; }
        public Nullable<decimal> PRONO { get; set; }
        public Nullable<decimal> PANO { get; set; }
        public Nullable<decimal> PONO { get; set; }
        public Nullable<decimal> POSNO { get; set; }
        public Nullable<decimal> AUSGNO { get; set; }
        public Nullable<decimal> VORGNO { get; set; }
        public string TXTNUMMER { get; set; }
        public Nullable<decimal> ALAGER0 { get; set; }
        public Nullable<decimal> ALAGER1 { get; set; }
        public Nullable<decimal> ALAGER2 { get; set; }
        public Nullable<decimal> ALAGER3 { get; set; }
        public Nullable<decimal> ALAGER4 { get; set; }
        public Nullable<decimal> ALAGER5 { get; set; }
        public string ALAGERN { get; set; }
        public Nullable<decimal> APLACEI { get; set; }
        public string COSTCENTER { get; set; }
        public Nullable<decimal> DELIVERYSTATUS { get; set; }
        public Nullable<decimal> EINHEIT { get; set; }
        public string GRPNAME { get; set; }
        public decimal GRPNO { get; set; }
        public Nullable<System.DateTime> LDATUM { get; set; }
        public string LNUMBER { get; set; }
        public string LOGINFO { get; set; }
        public string LOGINFO2 { get; set; }
        public Nullable<decimal> LOGSTATUS { get; set; }
        public Nullable<System.DateTime> LTIME { get; set; }
        public string MASSEINH { get; set; }
        public Nullable<decimal> MENGE0 { get; set; }
        public Nullable<decimal> MENGE1 { get; set; }
        public Nullable<decimal> MENGE2 { get; set; }
        public Nullable<decimal> MENGE3 { get; set; }
        public Nullable<decimal> MENGE4 { get; set; }
        public Nullable<decimal> MENGE5 { get; set; }
        public Nullable<decimal> MENGE6 { get; set; }
        public Nullable<System.DateTime> MSTDATE { get; set; }
        public string MSTOCK { get; set; }
        public Nullable<decimal> PACKDIM { get; set; }
        public Nullable<decimal> PAPERM { get; set; }
        public Nullable<decimal> PPREIS { get; set; }
        public Nullable<decimal> PREIS0 { get; set; }
        public Nullable<decimal> PREIS1 { get; set; }
        public Nullable<decimal> PREIS2 { get; set; }
        public Nullable<decimal> PREIS3 { get; set; }
        public Nullable<decimal> PREIS4 { get; set; }
        public Nullable<decimal> PREIS5 { get; set; }
        public Nullable<decimal> PREIS6 { get; set; }
        public string PRONAME { get; set; }
        public Nullable<decimal> TRANSACTIONTYPE { get; set; }
        public string TYPE { get; set; }
        public string WORKPLACE { get; set; }
        public Nullable<decimal> WPLACENO { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
