//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartTrace
    {
        public int PartTrace_Reference { get; set; }
        public string Record_Type { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Specification { get; set; }
        public string Form { get; set; }
        public string Batch_Number { get; set; }
        public string Supplier_Batch_Number { get; set; }
        public string Advice_Note { get; set; }
        public string Suppliers_CoC { get; set; }
        public string Notes { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<int> PStock_Reference { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<bool> Use_Internal_Batch_No { get; set; }
    }
}
