//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PE_WORK
    {
        public decimal NO { get; set; }
        public string PERSNO { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> CALNO { get; set; }
        public string CNTRYSIGN { get; set; }
        public Nullable<decimal> CONO { get; set; }
        public Nullable<decimal> COSTNO { get; set; }
        public Nullable<decimal> COSTPH1 { get; set; }
        public Nullable<decimal> COSTPH2 { get; set; }
        public Nullable<decimal> COSTPH3 { get; set; }
        public Nullable<decimal> DEPTNO { get; set; }
        public Nullable<decimal> EFC { get; set; }
        public string FAX { get; set; }
        public Nullable<decimal> GROUPNO { get; set; }
        public Nullable<decimal> INTMAIL1 { get; set; }
        public string MODEM { get; set; }
        public Nullable<System.DateTime> PDAYDAT1 { get; set; }
        public Nullable<System.DateTime> PDAYDAT2 { get; set; }
        public Nullable<System.DateTime> PDAYDAT3 { get; set; }
        public string PDAYINF1 { get; set; }
        public string PDAYINF2 { get; set; }
        public string PDAYINF3 { get; set; }
        public string PEINFO { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string PLACE { get; set; }
        public string POSITION { get; set; }
        public string POSTCODE { get; set; }
        public string SALUTE { get; set; }
        public string SBREAK { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public Nullable<decimal> SHIFTNO { get; set; }
        public Nullable<decimal> STATUS1 { get; set; }
        public Nullable<decimal> STATUS2 { get; set; }
        public Nullable<decimal> STATUS3 { get; set; }
        public string STREET { get; set; }
        public Nullable<decimal> WENDH { get; set; }
        public Nullable<System.DateTime> WENDT { get; set; }
        public Nullable<decimal> WSTARTH { get; set; }
        public Nullable<System.DateTime> WSTARTT { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
    }
}
