//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class POrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POrder()
        {
            this.PItems = new HashSet<PItem>();
        }
    
        public int POrder_Reference { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string User_Reference { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<int> Supplier_Reference { get; set; }
        public Nullable<int> Contact_Reference { get; set; }
        public Nullable<int> Location_Reference { get; set; }
        public int Client_Reference { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Last_Modified { get; set; }
        public byte[] Notes1 { get; set; }
        public byte[] Notes2 { get; set; }
        public Nullable<bool> COC_Required { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Last_Modified { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public Nullable<int> NumFileAttachments { get; set; }
        public Nullable<int> NumBrokenLinks { get; set; }
        public int Revision { get; set; }
        public int Ack_Revision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PItem> PItems { get; set; }
    }
}
