//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_OBJECTS
    {
        public decimal NO { get; set; }
        public decimal OBJTYP { get; set; }
        public Nullable<decimal> FKID { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> MEASUREMENT { get; set; }
        public Nullable<decimal> ZOOMPERC { get; set; }
        public Nullable<decimal> LPEN { get; set; }
        public string LTYP { get; set; }
        public Nullable<decimal> X1 { get; set; }
        public Nullable<decimal> Y1 { get; set; }
        public Nullable<decimal> X2 { get; set; }
        public Nullable<decimal> Y2 { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> BMPX1 { get; set; }
        public Nullable<decimal> BMPY1 { get; set; }
        public Nullable<decimal> BMPX2 { get; set; }
        public Nullable<decimal> BMPY2 { get; set; }
        public Nullable<decimal> BMPWIDTH { get; set; }
        public Nullable<decimal> BMPHEIGHT { get; set; }
        public Nullable<decimal> STOCKINANGLE { get; set; }
        public Nullable<decimal> STOCKOUTANGLE { get; set; }
        public Nullable<decimal> OBJECTANGLE { get; set; }
        public Nullable<decimal> TRANSPARENT1 { get; set; }
        public Nullable<decimal> TRANSPARENT2 { get; set; }
        public Nullable<decimal> TRANSPARENT3 { get; set; }
        public Nullable<decimal> TRANSPARENT4 { get; set; }
        public Nullable<decimal> TRANSPARENT5 { get; set; }
        public Nullable<decimal> TRANSPARENT6 { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> LAYNO { get; set; }
    }
}
