//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_VECTORMAP
    {
        public decimal OBJNO { get; set; }
        public Nullable<decimal> PEN { get; set; }
        public Nullable<decimal> X1 { get; set; }
        public Nullable<decimal> Y1 { get; set; }
        public Nullable<decimal> X2 { get; set; }
        public Nullable<decimal> Y2 { get; set; }
        public Nullable<decimal> LAYNO { get; set; }
    }
}
