//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_SIMU
    {
        public decimal NO { get; set; }
        public decimal LAYNO { get; set; }
        public Nullable<decimal> ETYPE { get; set; }
        public Nullable<decimal> ORNO { get; set; }
        public Nullable<decimal> OPNO { get; set; }
        public Nullable<decimal> OPNO2 { get; set; }
        public Nullable<System.DateTime> STIME { get; set; }
        public Nullable<System.DateTime> ETIME { get; set; }
        public Nullable<decimal> ZEIT { get; set; }
        public Nullable<decimal> TBNO { get; set; }
        public Nullable<decimal> RESTYPE { get; set; }
        public string DESCR { get; set; }
    }
}
