//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_PERS
    {
        public decimal NO { get; set; }
        public decimal OPNO { get; set; }
        public Nullable<decimal> WORKNO { get; set; }
        public Nullable<decimal> PERSPERC { get; set; }
        public Nullable<decimal> PERSABS { get; set; }
        public Nullable<decimal> USEABS { get; set; }
    }
}
