//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PW_PASS
    {
        public decimal NO { get; set; }
        public string BUNIT { get; set; }
        public string FIRSTNAME { get; set; }
        public string PASSCOMP { get; set; }
        public string PASSDEL { get; set; }
        public string PASSEDIT { get; set; }
        public string PASSOPEN { get; set; }
        public string PASSWORD { get; set; }
        public string SURNAME { get; set; }
        public string USERRIGHTS { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
    }
}
