//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.QComponents = new HashSet<QComponent>();
            this.QMaterials = new HashSet<QMaterial>();
            this.QParts = new HashSet<QPart>();
            this.QSubContracts = new HashSet<QSubContract>();
            this.QTools = new HashSet<QTool>();
            this.QWCentres = new HashSet<QWCentre>();
        }
    
        public int Quote_Reference { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Prepared { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string User_Reference { get; set; }
        public string Group_Reference { get; set; }
        public bool Main { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public string Drawing_Number { get; set; }
        public string Drawing_Issue { get; set; }
        public Nullable<decimal> WCentre_Total_Cost { get; set; }
        public Nullable<decimal> Material_Total_Cost { get; set; }
        public Nullable<decimal> Part_Total_Cost { get; set; }
        public Nullable<decimal> SubContract_Total_Cost { get; set; }
        public Nullable<decimal> Tool_Total_Cost { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public byte[] Notes { get; set; }
        public byte[] Public_Notes { get; set; }
        public Nullable<int> Customer_Reference { get; set; }
        public Nullable<int> Location_Reference { get; set; }
        public Nullable<int> Contact_Reference { get; set; }
        public int Client_Reference { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Part_Number { get; set; }
        public string Part_Issue { get; set; }
        public Nullable<double> Method { get; set; }
        public Nullable<System.DateTime> Schedule_Date { get; set; }
        public string Status { get; set; }
        public string Customer_Enquiry_Number { get; set; }
        public string Method_Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<decimal> Assembly_Cost { get; set; }
        public Nullable<decimal> Assembly_WCentre_Cost { get; set; }
        public Nullable<decimal> Assembly_Material_Cost { get; set; }
        public Nullable<decimal> Assembly_Part_Cost { get; set; }
        public Nullable<decimal> Assembly_SubCon_Cost { get; set; }
        public Nullable<decimal> Assembly_Tool_Cost { get; set; }
        public Nullable<double> Discount_Applied { get; set; }
        public Nullable<double> Customer_Discount_Applied { get; set; }
        public byte[] Long_Description { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public string Lead_Time { get; set; }
        public string Pricing_Unit { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Last_Modified { get; set; }
        public Nullable<double> order_Quantity { get; set; }
        public Nullable<int> Originating_Quote_Reference { get; set; }
        public Nullable<int> Part_Reference { get; set; }
        public Nullable<int> NumFileAttachments { get; set; }
        public Nullable<int> NumBrokenLinks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QComponent> QComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QMaterial> QMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPart> QParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QSubContract> QSubContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QTool> QTools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QWCentre> QWCentres { get; set; }
    }
}
