//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_field
    {
        public string table_name { get; set; }
        public string field_name { get; set; }
        public string field_alias { get; set; }
        public string datatype { get; set; }
        public string selectable { get; set; }
        public string searchable { get; set; }
        public string sortable { get; set; }
        public string autosearch { get; set; }
        public string mandatory { get; set; }
    }
}
