//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_join
    {
        public string table_name1 { get; set; }
        public string table_name2 { get; set; }
        public string join_type { get; set; }
        public string field_names1 { get; set; }
        public string operators { get; set; }
        public string field_names2 { get; set; }
    }
}
