//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reject
    {
        public int Reject_Reference { get; set; }
        public string Reject_Prefix { get; set; }
        public Nullable<int> Reject_Number { get; set; }
        public string Reject_Suffix { get; set; }
        public Nullable<System.DateTime> Date_Raised { get; set; }
        public Nullable<System.DateTime> Date_Closed { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }
        public string Raised_By { get; set; }
        public bool Other { get; set; }
        public bool Customer { get; set; }
        public bool Supplier { get; set; }
        public string OtherText { get; set; }
        public Nullable<int> Customer_Reference { get; set; }
        public Nullable<int> Cust_Contact_Ref { get; set; }
        public Nullable<int> Cust_Location_Ref { get; set; }
        public Nullable<int> WOrder_Reference { get; set; }
        public Nullable<int> Supplier_Reference { get; set; }
        public Nullable<int> Supplier_Contact_Ref { get; set; }
        public Nullable<int> Supplier_Location_Ref { get; set; }
        public Nullable<int> POrder_Reference { get; set; }
        public Nullable<int> Concession_Reference { get; set; }
        public Nullable<int> NonConf_Reference { get; set; }
        public Nullable<int> Complaint_Reference { get; set; }
        public byte[] Reason { get; set; }
        public byte[] Action { get; set; }
        public byte[] Prevention { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<int> Procedure_Reference { get; set; }
        public string Order_Description { get; set; }
        public string Drawing_No { get; set; }
        public string Drawing_Issue { get; set; }
        public string Part_No { get; set; }
        public string Part_Issue { get; set; }
        public string Customers_Order_No { get; set; }
        public string Customers_Order_Item { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<double> Quantity_On_Order { get; set; }
        public Nullable<double> Quantity_Rejected { get; set; }
        public string WOrder_User_Ref { get; set; }
        public string POrder_User_Ref { get; set; }
        public Nullable<int> Reject_Category_Reference { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
    }
}
