//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ
    {
        public int RFQ_Reference { get; set; }
        public string User_Reference { get; set; }
        public Nullable<int> Plan_Reference { get; set; }
        public string Send_Method { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Supplier_Reference { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Sent_To_Supplier { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> client_reference { get; set; }
        public Nullable<int> Location_reference { get; set; }
        public Nullable<int> Contact_reference { get; set; }
        public Nullable<int> Pitem_reference { get; set; }
        public Nullable<decimal> Accepted_Cost { get; set; }
        public Nullable<int> Worder_Reference { get; set; }
        public string WoUser_reference { get; set; }
        public string QUser_Reference { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Last_modified { get; set; }
        public Nullable<int> quote_reference { get; set; }
        public string POrder { get; set; }
        public Nullable<System.DateTime> Porder_Date { get; set; }
    }
}
