//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_Item
    {
        public int RFQ_ITEM_ID { get; set; }
        public Nullable<int> RFQ_Reference { get; set; }
        public string Notes { get; set; }
        public int WOMaterial_Reference { get; set; }
        public int WOPart_Reference { get; set; }
        public int WOSubcontract_Reference { get; set; }
        public int Material_Reference { get; set; }
        public int Part_reference { get; set; }
        public int QPart_Reference { get; set; }
        public int QMaterial_Reference { get; set; }
        public int QSubcontract_Reference { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Accepted_Cost { get; set; }
        public Nullable<int> Accepted_Quantity { get; set; }
        public string Form { get; set; }
        public Nullable<int> Costcentre_Reference { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string UsedFor { get; set; }
        public Nullable<int> subcontract_reference { get; set; }
        public Nullable<int> QTool_reference { get; set; }
        public Nullable<int> WOTool_reference { get; set; }
        public string Description { get; set; }
        public string worder_reference { get; set; }
        public string Drawing_Number { get; set; }
        public string Drawing_Issue { get; set; }
        public string Part_Number { get; set; }
        public string Part_Issue { get; set; }
        public string Specification { get; set; }
    
        public virtual RFQ_Item RFQ_Item1 { get; set; }
        public virtual RFQ_Item RFQ_Item2 { get; set; }
    }
}
