//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_Plan
    {
        public int Plan__Reference { get; set; }
        public System.DateTime Date_Created { get; set; }
        public int Created_By { get; set; }
        public int Owned_By { get; set; }
        public int Last_Updated_By { get; set; }
        public System.DateTime Required_By_Date { get; set; }
        public bool Processed { get; set; }
        public string Notes { get; set; }
    }
}
