//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_CLIENT_WORKCENTRES
    {
        public int SFCD_Client_WorkCentre_ID { get; set; }
        public int SFDCClientRef { get; set; }
        public string WCentre_Reference { get; set; }
        public Nullable<int> GroupRef { get; set; }
    }
}
