//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_CLIENT_RECENT_USERS
    {
        public int ID { get; set; }
        public string ClientIdentifier { get; set; }
        public int EMPLOYEE_REF { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
