//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_STOCK
    {
        public decimal NO { get; set; }
        public Nullable<decimal> ARTNO { get; set; }
        public string PLACE { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string CNAME { get; set; }
        public string CHNAME { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CHDATE { get; set; }
        public Nullable<decimal> MANDANTNO { get; set; }
        public Nullable<System.DateTime> INCDATE { get; set; }
        public Nullable<decimal> WAREHOUSE { get; set; }
        public Nullable<decimal> OPNO { get; set; }
    }
}
