//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPerformance
    {
        public int Supplier_Performance_Ref { get; set; }
        public Nullable<int> POrder_Reference { get; set; }
        public Nullable<int> PItem_Reference { get; set; }
        public string User_Reference { get; set; }
        public Nullable<int> Supplier_Reference { get; set; }
        public Nullable<System.DateTime> Date_Raised { get; set; }
        public Nullable<System.DateTime> Date_Requested { get; set; }
        public Nullable<System.DateTime> Date_Delivered { get; set; }
        public string Description { get; set; }
        public string Specification { get; set; }
        public string Drawing_Number { get; set; }
        public string Drawing_Issue { get; set; }
        public Nullable<double> Quantity_Ordered { get; set; }
        public string Order_Notes { get; set; }
        public Nullable<double> Quantity_Delivered { get; set; }
        public Nullable<double> Qty_Passed_Inspection { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Rating { get; set; }
        public Nullable<double> Inspection_High { get; set; }
        public Nullable<double> Inspection_Low { get; set; }
        public bool Concession_Applies { get; set; }
        public Nullable<int> Concession_Reference { get; set; }
        public bool NonConformance_Applies { get; set; }
        public Nullable<int> NonConformance_Reference { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<int> Procedure_Reference { get; set; }
        public bool Reject_Applies { get; set; }
        public Nullable<int> Reject_Reference { get; set; }
        public bool Complaint_Applies { get; set; }
        public Nullable<int> Complaint_Reference { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Number { get; set; }
        public string Suffix { get; set; }
    }
}
