//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Codes
    {
        public int Reason_Code_ID { get; set; }
        public string Type { get; set; }
        public string Reason_Code { get; set; }
        public string Description { get; set; }
    }
}
