//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int Training_Reference { get; set; }
        public Nullable<int> Employee_Reference { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Training { get; set; }
        public Nullable<double> Number_Of_Days { get; set; }
        public string Nature { get; set; }
        public string Outcome { get; set; }
        public string Comments { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<int> Client_Reference { get; set; }
        public Nullable<int> Procedure_Reference { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Next_Activity_Date { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Number { get; set; }
        public string Suffix { get; set; }
    }
}
