//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TricornEntities : DbContext
    {
        public TricornEntities()
            : base("name=TricornEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ART_CUSTOMER> ART_CUSTOMER { get; set; }
        public virtual DbSet<ART_DELQUOTATION> ART_DELQUOTATION { get; set; }
        public virtual DbSet<ART_LTEXT> ART_LTEXT { get; set; }
        public virtual DbSet<ART_PLNAME> ART_PLNAME { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditItem> AuditItems { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<CA_CAPACITY> CA_CAPACITY { get; set; }
        public virtual DbSet<CA_HOLIDAY> CA_HOLIDAY { get; set; }
        public virtual DbSet<CA_WEEKPLAN> CA_WEEKPLAN { get; set; }
        public virtual DbSet<CalibKeysDetail> CalibKeysDetails { get; set; }
        public virtual DbSet<CalibrationEquipment> CalibrationEquipments { get; set; }
        public virtual DbSet<CalibrationHistory> CalibrationHistories { get; set; }
        public virtual DbSet<CalibrationProcedure> CalibrationProcedures { get; set; }
        public virtual DbSet<CalibrationUsage> CalibrationUsages { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Concession> Concessions { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Cost_Centre> Cost_Centre { get; set; }
        public virtual DbSet<CP_Weekly> CP_Weekly { get; set; }
        public virtual DbSet<CU_ACCOUNT> CU_ACCOUNT { get; set; }
        public virtual DbSet<CU_BEM> CU_BEM { get; set; }
        public virtual DbSet<CU_CNTRY> CU_CNTRY { get; set; }
        public virtual DbSet<CU_COTYP> CU_COTYP { get; set; }
        public virtual DbSet<CU_INFO> CU_INFO { get; set; }
        public virtual DbSet<CU_MAIL> CU_MAIL { get; set; }
        public virtual DbSet<CU_PERS> CU_PERS { get; set; }
        public virtual DbSet<CU_VERS> CU_VERS { get; set; }
        public virtual DbSet<CustomCommand> CustomCommands { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Currency> Customer_Currency { get; set; }
        public virtual DbSet<CustomerSatisfaction> CustomerSatisfactions { get; set; }
        public virtual DbSet<CustomerSatisfactionDetail> CustomerSatisfactionDetails { get; set; }
        public virtual DbSet<DefaultWorkingHr> DefaultWorkingHrs { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<DItem> DItems { get; set; }
        public virtual DbSet<DItemBuiltPartTrace> DItemBuiltPartTraces { get; set; }
        public virtual DbSet<DItemMatTrace> DItemMatTraces { get; set; }
        public virtual DbSet<DItemPartTrace> DItemPartTraces { get; set; }
        public virtual DbSet<DItemSubConTrace> DItemSubConTraces { get; set; }
        public virtual DbSet<DItemToolTrace> DItemToolTraces { get; set; }
        public virtual DbSet<DMethod> DMethods { get; set; }
        public virtual DbSet<DNote> DNotes { get; set; }
        public virtual DbSet<DocNote> DocNotes { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<EAddress> EAddresses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Details> Employee_Details { get; set; }
        public virtual DbSet<FactoryDayPlan> FactoryDayPlans { get; set; }
        public virtual DbSet<FAG_DETAIL> FAG_DETAIL { get; set; }
        public virtual DbSet<FAG_SALESMAN> FAG_SALESMAN { get; set; }
        public virtual DbSet<FAG_TRANSACTIONLOCKING> FAG_TRANSACTIONLOCKING { get; set; }
        public virtual DbSet<FAG_UNILOG> FAG_UNILOG { get; set; }
        public virtual DbSet<FI_ACCOUNT> FI_ACCOUNT { get; set; }
        public virtual DbSet<GKN_PROJECT> GKN_PROJECT { get; set; }
        public virtual DbSet<IN_KASSE> IN_KASSE { get; set; }
        public virtual DbSet<InvItem> InvItems { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<IS_CAL> IS_CAL { get; set; }
        public virtual DbSet<IS_NUM> IS_NUM { get; set; }
        public virtual DbSet<IS_SETUP> IS_SETUP { get; set; }
        public virtual DbSet<LB_DC> LB_DC { get; set; }
        public virtual DbSet<LB_FUNCTION> LB_FUNCTION { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MaintenanceHistory> MaintenanceHistories { get; set; }
        public virtual DbSet<MaintenanceMachine> MaintenanceMachines { get; set; }
        public virtual DbSet<MaintenanceProcedure> MaintenanceProcedures { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MDC_EVENTSTRUCT> MDC_EVENTSTRUCT { get; set; }
        public virtual DbSet<MDC_FUNCTIONMAPPING> MDC_FUNCTIONMAPPING { get; set; }
        public virtual DbSet<MDC_TERMINALID> MDC_TERMINALID { get; set; }
        public virtual DbSet<MStock> MStocks { get; set; }
        public virtual DbSet<MWithdrawal> MWithdrawals { get; set; }
        public virtual DbSet<Nominal_codes> Nominal_codes { get; set; }
        public virtual DbSet<Nonconformancy> Nonconformancies { get; set; }
        public virtual DbSet<Notifier> Notifiers { get; set; }
        public virtual DbSet<OG_ORGA> OG_ORGA { get; set; }
        public virtual DbSet<OG_ORGADOC> OG_ORGADOC { get; set; }
        public virtual DbSet<OP_CNC> OP_CNC { get; set; }
        public virtual DbSet<OP_SPC> OP_SPC { get; set; }
        public virtual DbSet<OR_ART> OR_ART { get; set; }
        public virtual DbSet<OR_CALC> OR_CALC { get; set; }
        public virtual DbSet<OR_CHARGE> OR_CHARGE { get; set; }
        public virtual DbSet<OR_GRPTYP> OR_GRPTYP { get; set; }
        public virtual DbSet<OR_OPNAME> OR_OPNAME { get; set; }
        public virtual DbSet<OR_OPTYPE> OR_OPTYPE { get; set; }
        public virtual DbSet<OR_PROJ> OR_PROJ { get; set; }
        public virtual DbSet<OR_SERIAL> OR_SERIAL { get; set; }
        public virtual DbSet<Order_Events> Order_Events { get; set; }
        public virtual DbSet<PA_ARTGRP> PA_ARTGRP { get; set; }
        public virtual DbSet<PA_ARTHIS> PA_ARTHIS { get; set; }
        public virtual DbSet<PA_ARTLIEF> PA_ARTLIEF { get; set; }
        public virtual DbSet<PA_ARTPOS> PA_ARTPOS { get; set; }
        public virtual DbSet<PA_ARTTYP> PA_ARTTYP { get; set; }
        public virtual DbSet<PA_DPD> PA_DPD { get; set; }
        public virtual DbSet<PA_FIBU> PA_FIBU { get; set; }
        public virtual DbSet<PA_FIT> PA_FIT { get; set; }
        public virtual DbSet<PA_PACKAGING> PA_PACKAGING { get; set; }
        public virtual DbSet<PA_PAPER> PA_PAPER { get; set; }
        public virtual DbSet<PA_POSIT> PA_POSIT { get; set; }
        public virtual DbSet<PA_STLB> PA_STLB { get; set; }
        public virtual DbSet<PA_TEXTE> PA_TEXTE { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartTrace> PartTraces { get; set; }
        public virtual DbSet<PE_GROUP> PE_GROUP { get; set; }
        public virtual DbSet<PE_MAPPING> PE_MAPPING { get; set; }
        public virtual DbSet<PE_WORK> PE_WORK { get; set; }
        public virtual DbSet<PE_WPLACE> PE_WPLACE { get; set; }
        public virtual DbSet<PItem> PItems { get; set; }
        public virtual DbSet<POrder> POrders { get; set; }
        public virtual DbSet<PRM_LAYOUTS> PRM_LAYOUTS { get; set; }
        public virtual DbSet<PRM_OBJECTS> PRM_OBJECTS { get; set; }
        public virtual DbSet<PRM_PERS> PRM_PERS { get; set; }
        public virtual DbSet<PRM_SIMU> PRM_SIMU { get; set; }
        public virtual DbSet<PRM_TRANSBOX> PRM_TRANSBOX { get; set; }
        public virtual DbSet<PRM_TRANSSYS> PRM_TRANSSYS { get; set; }
        public virtual DbSet<PRM_WAYCACHE> PRM_WAYCACHE { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<PStock> PStocks { get; set; }
        public virtual DbSet<PW_PASS> PW_PASS { get; set; }
        public virtual DbSet<PWithdrawal> PWithdrawals { get; set; }
        public virtual DbSet<QComponent> QComponents { get; set; }
        public virtual DbSet<QMaterial> QMaterials { get; set; }
        public virtual DbSet<QPart> QParts { get; set; }
        public virtual DbSet<QSubContract> QSubContracts { get; set; }
        public virtual DbSet<QTool> QTools { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<QWCentre> QWCentres { get; set; }
        public virtual DbSet<rb_field> rb_field { get; set; }
        public virtual DbSet<rb_folder> rb_folder { get; set; }
        public virtual DbSet<rb_item> rb_item { get; set; }
        public virtual DbSet<rb_join> rb_join { get; set; }
        public virtual DbSet<rb_table> rb_table { get; set; }
        public virtual DbSet<ReasonCodeType> ReasonCodeTypes { get; set; }
        public virtual DbSet<RecordKey> RecordKeys { get; set; }
        public virtual DbSet<RejectCategory> RejectCategories { get; set; }
        public virtual DbSet<Reject> Rejects { get; set; }
        public virtual DbSet<RFQ> RFQs { get; set; }
        public virtual DbSet<RFQ_Item> RFQ_Item { get; set; }
        public virtual DbSet<RFQ_Plan> RFQ_Plan { get; set; }
        public virtual DbSet<SatisfactionCategory> SatisfactionCategories { get; set; }
        public virtual DbSet<SFDC_CLIENT_RECENT_USERS> SFDC_CLIENT_RECENT_USERS { get; set; }
        public virtual DbSet<SFDC_CLIENT_WORKCENTRES> SFDC_CLIENT_WORKCENTRES { get; set; }
        public virtual DbSet<SFDC_CLIENTS> SFDC_CLIENTS { get; set; }
        public virtual DbSet<SFDC_GROUPS> SFDC_GROUPS { get; set; }
        public virtual DbSet<SH_DPD> SH_DPD { get; set; }
        public virtual DbSet<ST_PLACE> ST_PLACE { get; set; }
        public virtual DbSet<ST_STOCK> ST_STOCK { get; set; }
        public virtual DbSet<Stock_Categories> Stock_Categories { get; set; }
        public virtual DbSet<STrace> STraces { get; set; }
        public virtual DbSet<SubContract> SubContracts { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierPerformance> SupplierPerformances { get; set; }
        public virtual DbSet<System_Codes> System_Codes { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Tricorn_User_Acct> Tricorn_User_Acct { get; set; }
        public virtual DbSet<TricornSession> TricornSessions { get; set; }
        public virtual DbSet<TTrace> TTraces { get; set; }
        public virtual DbSet<UpgradeInfo> UpgradeInfoes { get; set; }
        public virtual DbSet<VAT_Rates> VAT_Rates { get; set; }
        public virtual DbSet<Warning> Warnings { get; set; }
        public virtual DbSet<WCentre> WCentres { get; set; }
        public virtual DbSet<WH_INT> WH_INT { get; set; }
        public virtual DbSet<WOComponent> WOComponents { get; set; }
        public virtual DbSet<WOInspection> WOInspections { get; set; }
        public virtual DbSet<WOMaterial> WOMaterials { get; set; }
        public virtual DbSet<WOOperAct> WOOperActs { get; set; }
        public virtual DbSet<WOPart> WOParts { get; set; }
        public virtual DbSet<WOrder> WOrders { get; set; }
        public virtual DbSet<WOSubContract> WOSubContracts { get; set; }
        public virtual DbSet<WOTool> WOTools { get; set; }
        public virtual DbSet<WOWCentre> WOWCentres { get; set; }
        public virtual DbSet<WP_GROUP> WP_GROUP { get; set; }
        public virtual DbSet<WP_MAGRP> WP_MAGRP { get; set; }
        public virtual DbSet<Break_Times> Break_Times { get; set; }
        public virtual DbSet<DBVersion> DBVersions { get; set; }
        public virtual DbSet<DiscountDetail> DiscountDetails { get; set; }
        public virtual DbSet<JIS_ADRESSEN> JIS_ADRESSEN { get; set; }
        public virtual DbSet<JIS_FERTIGUNG> JIS_FERTIGUNG { get; set; }
        public virtual DbSet<option> options { get; set; }
        public virtual DbSet<OR_FRAG> OR_FRAG { get; set; }
        public virtual DbSet<Param> Params { get; set; }
        public virtual DbSet<PRM_VECTORMAP> PRM_VECTORMAP { get; set; }
        public virtual DbSet<WCentreCost> WCentreCosts { get; set; }
    }
}
