//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tricorn_User_Acct
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Employee_Reference { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<bool> Administrator { get; set; }
        public Nullable<bool> Take_Ownership_Quotes { get; set; }
        public Nullable<bool> Take_Ownwership_Worder { get; set; }
        public Nullable<bool> Take_Ownership_PO { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<bool> RestrictedView { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<bool> EmailQuotes { get; set; }
        public Nullable<bool> EmailPO { get; set; }
        public Nullable<bool> EmailAcks { get; set; }
        public Nullable<bool> EmailCOC { get; set; }
        public Nullable<bool> EmailInvoices { get; set; }
        public Nullable<bool> EmailDeliveryNotes { get; set; }
        public Nullable<bool> View_Messages { get; set; }
        public Nullable<bool> Administer_Messages { get; set; }
        public Nullable<bool> Take_Ownership_Delivery_Notes { get; set; }
        public Nullable<bool> Take_Ownership_invoices { get; set; }
        public Nullable<bool> Take_Ownership_Customers { get; set; }
        public Nullable<bool> Take_Ownership_Suppliers { get; set; }
        public Nullable<bool> Take_OwnerShip_Work_Centres { get; set; }
        public Nullable<bool> Take_Ownership_Material { get; set; }
        public Nullable<bool> Take_Ownership_Parts { get; set; }
        public Nullable<bool> Take_Ownership_SubContract { get; set; }
        public Nullable<bool> Take_Ownership_Discounts { get; set; }
        public Nullable<bool> Adminster_Account_Settings { get; set; }
        public Nullable<bool> Accounts_Access { get; set; }
        public bool Administer_Customers { get; set; }
        public bool Administer_Suppliers { get; set; }
        public bool Allowed_To_Deliver { get; set; }
        public bool Allowed_To_Invoice { get; set; }
        public bool Allowed_To_Add_Stock { get; set; }
        public bool Allowed_To_Hold { get; set; }
        public bool Allowed_To_Scrap { get; set; }
        public Nullable<bool> Allowed_To_RFQ { get; set; }
        public string RFQEmailBody { get; set; }
        public Nullable<bool> Take_Ownership_RFQ { get; set; }
        public Nullable<bool> Email_RFQs { get; set; }
        public Nullable<bool> View_Material_Button { get; set; }
        public Nullable<bool> View_WOMaterial_Tab { get; set; }
        public Nullable<bool> View_Part_Button { get; set; }
        public Nullable<bool> View_WOPart_Tab { get; set; }
        public Nullable<bool> View_SubCon_Button { get; set; }
        public Nullable<bool> View_WOSubCon_Tab { get; set; }
        public Nullable<bool> View_WOTool_Tab { get; set; }
        public Nullable<bool> View_POrder_Button { get; set; }
        public Nullable<bool> View_EUR_Button { get; set; }
        public Nullable<bool> FileAttachmentsAdmin { get; set; }
        public Nullable<bool> Access_Scheduler_Queue { get; set; }
        public Nullable<bool> Edit_WO_OP_Scheduler_Settings { get; set; }
        public Nullable<bool> Create_Capacity_WO { get; set; }
    }
}
