//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpgradeInfo
    {
        public int Upgrade_ref { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
