//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning
    {
        public int Warning_Reference { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
        public string Message_Text { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Severity { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Last_Modified { get; set; }
        public Nullable<bool> Expired { get; set; }
        public string Item_num { get; set; }
        public string Issue { get; set; }
    }
}
