//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCentre
    {
        public int WCentre_Reference { get; set; }
        public string Name { get; set; }
        public string Centre_Id { get; set; }
        public string Category { get; set; }
        public Nullable<double> Setting_Time { get; set; }
        public Nullable<double> Run_Time { get; set; }
        public Nullable<int> Inspection_Level { get; set; }
        public Nullable<decimal> Cost_Per_Hour { get; set; }
        public Nullable<double> Hours_Per_Week { get; set; }
        public Nullable<double> Uplift { get; set; }
        public Nullable<double> Schedule_Days { get; set; }
        public string Notes { get; set; }
        public int Client_Reference { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Last_Modified { get; set; }
        public bool External_Work { get; set; }
        public Nullable<decimal> WIP_Per_Hour { get; set; }
        public string Bitmap_Name { get; set; }
        public Nullable<decimal> Multi { get; set; }
        public Nullable<decimal> PRODHRS { get; set; }
        public Nullable<decimal> PALET { get; set; }
        public Nullable<System.DateTime> STARTZEIT { get; set; }
        public Nullable<decimal> LIEGEZEIT { get; set; }
        public Nullable<decimal> TERMNO { get; set; }
        public Nullable<decimal> TYP { get; set; }
        public Nullable<bool> Monitor { get; set; }
        public bool Subject_To_Breaks { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Owned_By { get; set; }
        public Nullable<int> Last_Modified { get; set; }
        public Nullable<decimal> WAITMODE { get; set; }
        public Nullable<int> NumFileAttachments { get; set; }
        public Nullable<int> NumBrokenLinks { get; set; }
        public Nullable<int> PlanningColour { get; set; }
        public Nullable<int> DefaultWorkingHrsId { get; set; }
        public Nullable<decimal> SPEEDFACTOR { get; set; }
        public Nullable<decimal> SPEEDMODE { get; set; }
        public bool IncludeInPlanning { get; set; }
        public Nullable<int> PlanningPosition { get; set; }
    }
}
