//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_INT
    {
        public decimal NO { get; set; }
        public string TRANS_ID { get; set; }
        public Nullable<decimal> TRANS_TYPE { get; set; }
        public string ARTNAME { get; set; }
        public string ARTDESCR { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> CONF_QTY { get; set; }
        public Nullable<decimal> UNIT { get; set; }
        public string WH_USER { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public Nullable<System.DateTime> CONF_DATE { get; set; }
        public Nullable<System.DateTime> BOOK_DATE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string LOCATION { get; set; }
    }
}
