//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOOperAct
    {
        public int WOTimes_Reference { get; set; }
        public Nullable<int> WOWCentre_Reference { get; set; }
        public Nullable<int> Employee_Reference { get; set; }
        public Nullable<System.DateTime> Date_Of_Activity { get; set; }
        public Nullable<double> Actual_Setting_Time { get; set; }
        public Nullable<double> Actual_Process_Time { get; set; }
        public Nullable<double> Actual_Total_Time { get; set; }
        public Nullable<double> Actual_Quantity_Finished { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Recorded_Start_Date { get; set; }
        public Nullable<System.DateTime> Recorded_End_Date { get; set; }
        public Nullable<System.DateTime> System_Start_Date { get; set; }
        public Nullable<System.DateTime> System_End_Date { get; set; }
        public Nullable<System.DateTime> Recorded_Start_Time { get; set; }
        public Nullable<System.DateTime> Recorded_End_Time { get; set; }
        public Nullable<System.DateTime> System_Start_Time { get; set; }
        public Nullable<System.DateTime> System_End_Time { get; set; }
        public bool IsLag { get; set; }
        public Nullable<int> Wait_Time_In_seconds { get; set; }
        public string Wait_Reason_Code { get; set; }
        public Nullable<bool> AutoClosed { get; set; }
        public Nullable<System.DateTime> shift_start { get; set; }
        public Nullable<System.DateTime> shift_Hours { get; set; }
        public Nullable<int> Time_To_Shift_End { get; set; }
        public Nullable<System.DateTime> shift_end { get; set; }
        public Nullable<int> Setting { get; set; }
        public Nullable<int> Scrap_Code { get; set; }
        public Nullable<int> Scrap { get; set; }
        public Nullable<int> Break_Code { get; set; }
        public string ClosedForBreakStatus { get; set; }
    }
}
