//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOWCentre
    {
        public int WOWCentre_Reference { get; set; }
        public int Sequence { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> Display_Sequence { get; set; }
        public Nullable<double> Setting_Time { get; set; }
        public Nullable<double> Run_Time { get; set; }
        public Nullable<decimal> Cost_Per_Hour { get; set; }
        public Nullable<double> Total_Hours { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<int> Inspection_Level { get; set; }
        public Nullable<double> Uplift { get; set; }
        public byte[] Notes { get; set; }
        public int WOrder_Reference { get; set; }
        public int WCentre_Reference { get; set; }
        public int Client_Reference { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Last_Modified { get; set; }
        public string Centre_Id { get; set; }
        public Nullable<double> Schedule_Days { get; set; }
        public Nullable<double> Actual_Total_Time { get; set; }
        public Nullable<decimal> Actual_Cost_Per_Hour { get; set; }
        public Nullable<double> Quantity_Finished { get; set; }
        public bool Operation_Finished { get; set; }
        public byte[] Sketch { get; set; }
        public Nullable<int> Operation_Number { get; set; }
        public Nullable<bool> External_Work { get; set; }
        public Nullable<int> RTEFontSize { get; set; }
        public string Program_Number { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<double> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<double> End_Time { get; set; }
        public Nullable<decimal> PTWAIT { get; set; }
        public Nullable<System.DateTime> PSTIMEMIN { get; set; }
        public Nullable<System.DateTime> PETIMEMAX { get; set; }
        public Nullable<decimal> OVERLAPPERC { get; set; }
        public Nullable<decimal> OVERLAP { get; set; }
        public Nullable<decimal> MATMISSING { get; set; }
        public Nullable<System.DateTime> MATETIME { get; set; }
        public string MATREMARK { get; set; }
        public Nullable<decimal> PREPMISSING { get; set; }
        public Nullable<System.DateTime> PREPETIME { get; set; }
        public string PREPREMARK { get; set; }
        public Nullable<decimal> TOOLMISSING { get; set; }
        public Nullable<System.DateTime> TOOLETIME { get; set; }
        public string TOOLREMARK { get; set; }
        public Nullable<decimal> DIV1MISSING { get; set; }
        public Nullable<System.DateTime> DIV1ETIME { get; set; }
        public string DIV1REMARK { get; set; }
        public Nullable<System.DateTime> PSTIMEMAX { get; set; }
        public string BITMAP { get; set; }
        public Nullable<bool> ExcludeFromAutoClose { get; set; }
        public Nullable<int> Originating_WOrder_Reference { get; set; }
        public Nullable<int> Originating_WOWCentre_Reference { get; set; }
        public Nullable<int> NumFileAttachments { get; set; }
        public Nullable<int> NumBrokenLinks { get; set; }
        public Nullable<double> TotalRun { get; set; }
        public Nullable<double> TotalSetup { get; set; }
        public Nullable<int> LastScrapCode { get; set; }
        public Nullable<int> LastBreakCode { get; set; }
        public Nullable<double> Quantity_Scrapped { get; set; }
        public int ParentPk { get; set; }
        public string SplitSeq { get; set; }
        public bool isParent { get; set; }
        public Nullable<System.DateTime> JITStartDate { get; set; }
        public Nullable<System.DateTime> JITEndDate { get; set; }
        public Nullable<System.DateTime> LASTMDCDATE { get; set; }
        public string ARDORGRESOURCE { get; set; }
        public Nullable<decimal> SPEEDFACTOR { get; set; }
        public Nullable<decimal> SPEEDMODE { get; set; }
        public Nullable<System.DateTime> Op_Started_On { get; set; }
        public Nullable<System.DateTime> Op_Finished_On { get; set; }
    
        public virtual WOrder WOrder { get; set; }
    }
}
