//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model.Tricorn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WP_GROUP
    {
        public decimal NO { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public string BITMAP { get; set; }
        public Nullable<decimal> CFLAG { get; set; }
        public string PASS1 { get; set; }
        public string PASS2 { get; set; }
        public string PASS3 { get; set; }
        public string PASS4 { get; set; }
        public string PASS5 { get; set; }
        public string PASS6 { get; set; }
        public string PASS7 { get; set; }
        public string PASS8 { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string USER3 { get; set; }
        public string USER4 { get; set; }
        public string USER5 { get; set; }
        public string USER6 { get; set; }
        public string USER7 { get; set; }
        public string USER8 { get; set; }
        public string CNAME { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> CHTIME { get; set; }
        public string CHNAME { get; set; }
    }
}
