//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalibrationResult()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int GaugeId { get; set; }
        public System.DateTime CalibratedOn { get; set; }
        public int CalibratedBy { get; set; }
        public double ExternalDeviationM1 { get; set; }
        public Nullable<double> ExternalDeviationM2 { get; set; }
        public Nullable<double> ExternalDeviationM3 { get; set; }
        public Nullable<double> ExternalDeviationM4 { get; set; }
        public Nullable<double> InternalDeviationM1 { get; set; }
        public Nullable<double> InternalDeviationM2 { get; set; }
        public Nullable<double> InternalDeviationM3 { get; set; }
        public Nullable<double> InternalDeviationM4 { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
