//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationResult
    {
        public int Id { get; set; }
        public int GaugeId { get; set; }
        public System.DateTime CalibratedOn { get; set; }
        public string ExternalReference { get; set; }
        public double ExpectedResult1 { get; set; }
        public double ActualResult1 { get; set; }
        public Nullable<double> ExpectedResult2 { get; set; }
        public Nullable<double> ActualResult2 { get; set; }
        public Nullable<double> ExpectedResult3 { get; set; }
        public Nullable<double> ActualResult3 { get; set; }
        public Nullable<double> ExpectedResult4 { get; set; }
        public Nullable<double> ActualResult4 { get; set; }
        public Nullable<double> ExpectedResult5 { get; set; }
        public Nullable<double> ActualResult5 { get; set; }
        public string Notes { get; set; }
    
        public virtual Gauge Gauge { get; set; }
    }
}
