//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPEEntities : DbContext
    {
        public CPEEntities()
            : base("name=CPEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalibrationMethod> CalibrationMethods { get; set; }
        public virtual DbSet<CalibrationResult> CalibrationResults { get; set; }
        public virtual DbSet<ClientSetting> ClientSettings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeWorkCentre> EmployeeWorkCentres { get; set; }
        public virtual DbSet<Gauge> Gauges { get; set; }
        public virtual DbSet<GaugeType> GaugeTypes { get; set; }
        public virtual DbSet<HolderGroup> HolderGroups { get; set; }
        public virtual DbSet<Holder> Holders { get; set; }
        public virtual DbSet<HolderTool> HolderTools { get; set; }
        public virtual DbSet<MachineGroup> MachineGroups { get; set; }
        public virtual DbSet<Method> Methods { get; set; }
        public virtual DbSet<NonConformance> NonConformances { get; set; }
        public virtual DbSet<NonConformanceType> NonConformanceTypes { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<OperationTool> OperationTools { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartVersion> PartVersions { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<RecentPart> RecentParts { get; set; }
        public virtual DbSet<RejectReason> RejectReasons { get; set; }
        public virtual DbSet<ToolGroup> ToolGroups { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<TricornTool> TricornTools { get; set; }
    }
}
