//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonConformance
    {
        public int Id { get; set; }
        public int NonConformanceTypeId { get; set; }
        public int RejectReasonId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> PartId { get; set; }
        public string WorksOrderNumber { get; set; }
        public string SalesOrderNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string CustomerReturnNumber { get; set; }
        public Nullable<System.DateTime> CustomerReturnDate { get; set; }
        public string ContactName { get; set; }
        public int RaisedBy { get; set; }
        public System.DateTime RaisedOn { get; set; }
        public int QuantityAffected { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeResponsibleId { get; set; }
        public string ImmediateAction { get; set; }
        public bool ImmediateActionComplete { get; set; }
        public string CorrectiveAction { get; set; }
        public bool CorrectiveActionComplete { get; set; }
        public string FinalDisposition { get; set; }
        public bool IsComplaintClosed { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual NonConformanceType NonConformanceType { get; set; }
        public virtual RejectReason RejectReason { get; set; }
    }
}
