//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPE.Data.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationTool
    {
        public int Id { get; set; }
        public int Position { get; set; }
        public int Offset { get; set; }
        public int UseOnePer { get; set; }
        public string Notes { get; set; }
        public int OperationId { get; set; }
        public Nullable<int> HolderId { get; set; }
        public int ToolId { get; set; }
    
        public virtual Holder Holder { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Tool Tool { get; set; }
    }
}
